### ISSUE TITLE
Improve Readme about custom scalar types

### ISSUE THREAD

**Issue by olLenz** [apollographql/apollo-android#819] opened 2018-02-05 13:09 UTC
I wanted to use a custom scalar type and followed the instructions of your readme ( https://github.com/apollographql/apollo-android#custom-scalar-types).

After doing the needed steps apollo didn't generate the new custom scalar type and I searched for some time until I found out, that you need to have a query using this custom scalar type before apollo will generate code for it. 
Would be nice if you could add this little fact to your documentation :)

**Comment by digitalbuddha** [comment] 2018-05-05 19:59
#910 has the new api, marking this as a dupe of #889

**Closed by digitalbuddha** 2018-05-05 19:59 UTC
Labels: Type: Documentation
