### ISSUE TITLE
Proposal: Add option to memoize toString()/hashCode()

### ISSUE THREAD

**Issue by hzsweers** [apollographql/apollo-android#420] opened 2017-04-16 23:45 UTC
Since the models are immutable, memoizing hashCode/toString() would be nice. This is a common use case for AutoValue's `@Memoized` extension as well, and would make its implementation a good reference.

**Comment by sav007** [comment] 2017-04-17 19:27
@hzsweers is this issue duplicate of this one  https://github.com/apollographql/apollo-android/issues/423

**Comment by hzsweers** [comment] 2017-04-17 20:07
Oh wat. Github gave me an error earlier so I opened this one in the process of trying again. Closed the other ¯\_(ツ)_/¯

**Closed** 2017-04-19 20:18 UTC
Labels: Type: compiler
