### ISSUE TITLE
NoSuchMethodError while generating code in 1.0.0-alpha3

### ISSUE THREAD

**Issue by scottkennedy** [apollographql/apollo-android#1113] opened 2018-11-14 19:33 UTC
`./gradlew graphql:generateDebugApolloClasses` works in alpha2, but with alpha3, fails with the following exception:

```
* What went wrong:
Execution failed for task ':graphql:generateDebugApolloClasses'.
> com.squareup.javapoet.ClassName.withoutAnnotations()Lcom/squareup/javapoet/ClassName;

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':graphql:generateDebugApolloClasses'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipCachedTaskExecuter.execute(SkipCachedTaskExecuter.java:105)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ResolveBuildCacheKeyExecuter.execute(ResolveBuildCacheKeyExecuter.java:79)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.NoSuchMethodError: com.squareup.javapoet.ClassName.withoutAnnotations()Lcom/squareup/javapoet/ClassName;
        at com.apollographql.apollo.compiler.ClassNames.parameterizedMapOf(ClassNames.kt:44)
        at com.apollographql.apollo.compiler.VariablesTypeSpecBuilder.valueMapFieldSpec(VariablesTypeSpecBuilder.kt:38)
        at com.apollographql.apollo.compiler.VariablesTypeSpecBuilder.build(VariablesTypeSpecBuilder.kt:21)
        at com.apollographql.apollo.compiler.OperationTypeSpecBuilder.addVariablesDefinition(OperationTypeSpecBuilder.kt:142)
        at com.apollographql.apollo.compiler.OperationTypeSpecBuilder.toTypeSpec(OperationTypeSpecBuilder.kt:28)
        at com.apollographql.apollo.compiler.ir.CodeGenerator$DefaultImpls.toTypeSpec$default(CodeGenerator.kt:6)
        at com.apollographql.apollo.compiler.GraphQLCompiler.writeJavaFiles(GraphQLCompiler.kt:66)
        at com.apollographql.apollo.compiler.GraphQLCompiler.write(GraphQLCompiler.kt:39)
        at com.apollographql.apollo.compiler.GraphQLCompiler$write.call(Unknown Source)
        at com.apollographql.apollo.gradle.ApolloClassGenerationTask$1.execute(ApolloClassGenerationTask.groovy:53)
        at com.apollographql.apollo.gradle.ApolloClassGenerationTask$1.execute(ApolloClassGenerationTask.groovy)
        at org.gradle.api.internal.changedetection.changes.RebuildIncrementalTaskInputs.doOutOfDate(RebuildIncrementalTaskInputs.java:45)
        at org.gradle.api.internal.changedetection.changes.StatefulIncrementalTaskInputs.outOfDate(StatefulIncrementalTaskInputs.java:32)
        at org.gradle.api.internal.changedetection.changes.RebuildIncrementalTaskInputs.outOfDate(RebuildIncrementalTaskInputs.java:29)
        at org.gradle.api.tasks.incremental.IncrementalTaskInputs$outOfDate.call(Unknown Source)
        at com.apollographql.apollo.gradle.ApolloClassGenerationTask.generateClasses(ApolloClassGenerationTask.groovy:38)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        ... 33 more
```

**Comment by sav007** [comment] 2018-11-20 00:01
Super strange as I can't reproduce this issue on sample project.

**Comment by lgawin** [comment] 2018-11-21 22:03
I spent some time to investigate the issue, as I faced the same `NoSuchMethodError` in my project. And here are the results of the investigation - it happens under specific circumstances:
* project is Android project with `com.android.tools.build:gradle:3.1+` applied (in root `build.gradle`)
* submodule containing graphql stuff (either android application `app` or any library) has `com.apollographql.apollo:apollo-gradle-plugin:1.0.0-alpha3`
* any query has arguments - e.g. `query Login($email: String!, $password: String!) {...`

This kind of setup causes that root module uses `javapoet-1.8.0` (it is a dependency of databinding added to `com.android.tools.build:gradle:3.1.0`) while submodule with graphql is using `javapoet-1.11.1`, and those require different versions of Java.

Maybe my fault is that I'm using `com.apollographql.apollo:apollo-gradle-plugin:1.0.0-alpha3` on submodule (@sav007 ???). Moving `classpath 'com.apollographql.apollo:apollo-gradle-plugin:1.0.0-alpha3'` from submodule's `build.gradle` to the **root** `build.gradle` buildscript dependencies helps. 
So I finish with:
```
buildscript {
  ext.apollo_version = "1.0.0-alpha3"
  repositories {
    google()
    jcenter()
  }
  dependencies {
    classpath 'com.android.tools.build:gradle:3.2.1'
    classpath "com.apollographql.apollo:apollo-gradle-plugin:$apollo_version"
  }
}
...
```
in root `build.gradle`
and
```
apply plugin: 'com.android.application' // or `com.android.library` or just `java` or `kotlin`
// optionally if Kotlin is in the project
//apply plugin: 'kotlin-android'
//apply plugin: 'kotlin-android-extensions'
apply plugin: 'com.apollographql.android'

dependencies {
  ...
  implementation "com.apollographql.apollo:apollo-runtime:$apollo_version"
  ...
}
...
```
in `graphql/build.gradle`.
If this is the case, it should probably be emphasized in the documentation.


Another workaround that seems to work is to force newer version of javapoet in root module by adding dependency next to the latest android gradle plugin
```
buildscript {
  repositories {
    google()
    jcenter()
  }
  dependencies {
    classpath 'com.android.tools.build:gradle:3.2.1'
    classpath 'com.squareup:javapoet:1.11.1'
  }
}
...
```
in root `build.gradle`
and
```
buildscript {
  ext.apollo_version = "1.0.0-alpha3"
  repositories {
    jcenter()
  }
  dependencies {
    classpath "com.apollographql.apollo:apollo-gradle-plugin:$apollo_version"
  }
}

apply plugin: 'com.android.application' // or `com.android.library` or just `java` or `kotlin`
// optionally if Kotlin is in the project
//apply plugin: 'kotlin-android'
//apply plugin: 'kotlin-android-extensions'
apply plugin: 'com.apollographql.android'

dependencies {
  ...
  implementation "com.apollographql.apollo:apollo-runtime:$apollo_version"
  ...
}
...
```
in `graphql/build.gradle`

**Comment by lgawin** [comment] 2018-11-21 23:39
Another workaround that seems to work is to force newer version of javapoet in **root** module by adding dependency next to the latest android gradle plugin
```
buildscript {
  repositories {
    google()
    jcenter()
  }
  dependencies {
    classpath 'com.android.tools.build:gradle:3.2.1'
    classpath 'com.squareup:javapoet:1.11.1'
  }
}
...
```
in root `build.gradle`
and
```
buildscript {
  ext.apollo_version = "1.0.0-alpha3"
  repositories {
    jcenter()
  }
  dependencies {
    classpath "com.apollographql.apollo:apollo-gradle-plugin:$apollo_version"
  }
}

apply plugin: 'com.android.application' // or `com.android.library` or just `java` or `kotlin`
// optionally if Kotlin is in the project
//apply plugin: 'kotlin-android'
//apply plugin: 'kotlin-android-extensions'
apply plugin: 'com.apollographql.android'

dependencies {
  ...
  implementation "com.apollographql.apollo:apollo-runtime:$apollo_version"
  ...
}
...
```
in `graphql/build.gradle`

@sav007 In case of using Kotlin DSL (as proposed here: #1120) this seems to be the only way to make it work with `javapoet-1.11.1`. The question is if `1.8.0` -> `1.11.1` is really a good move ... 🤔

**Comment by lgawin** [comment] 2018-11-23 12:56
I'm a bit wrong with my previous statement
> 
> @sav007 In case of using Kotlin DSL (as proposed here: #1120) this seems to be the only way to make it work with `javapoet-1.11.1`. 

It is possible to use `apollo-gradle-plugin` version `1.0.0-alpha3` with Kotlin DSL, I'll prepare some gists and some PR to the documentation to describe it.

**Comment by sav007** [comment] 2018-11-27 22:19
Could you guys check the latest snapshot version, it should be fixed now. I downgraded the version of Javapoet. Closing for now but feel free to re-open if it still the case.

**Closed by sav007** 2018-11-27 22:19 UTC
Labels: blocking
