### ISSUE TITLE
HTTP 400 Bad Request

### ISSUE THREAD

**Issue by alissonfpmorais** [apollographql/apollo-android#1181] opened 2019-01-16 21:04 UTC
I've changed my project dependency version from `1.0.0-alpha3` to `1.0.0-alpha4` makes the code to thrown `ApolloException`, returning `HTTP 400 Bad Request`.
Changing back, makes the whole code to run smoothly. What could be?

**Comment by sav007** [comment] 2019-01-17 00:12
well 400 comes from the server, smth it doesn't like. We did changed the actual payload we sent to the server, it might be that field `extensions` it doesn't like but it part of the spec.

**Comment by davidwinnicki-playster** [comment] 2019-01-17 16:15
I am also experiencing the same issue.
After changing to version `1.0.0-alpha4` all previously working requests now throw a `ApolloHttpException: HTTP 400`

**Comment by yankeppey** [comment] 2019-01-17 16:17
The same for my project.

**Comment by davidwinnicki-playster** [comment] 2019-01-17 16:42
I compared one of my queries between the 2 versions.

With 1.0.0-alpha3 this is sent:
`{"query":"query LocationQuery {  location {    __typename    country {      __typename      code    }  }}","operationName":"LocationQuery","variables":{}}`

With 1.0.0-alpha4 this is sent:
`{"operationName":"LocationQuery","variables":{},"extensions":{"persistedQuery":{"version":1,"sha256Hash":"ea1c08defd121be8b3555bb8a2d42ddd1d888df8db4d249c0500e3ca03171e10"}},"query":"query LocationQuery {  location {    __typename    country {      __typename      code    }  }}"}`

The difference is the new `extensions` field. Could this be the cause and if this is the expected behavior how should we deal with it?

**Comment by sosasang** [comment] 2019-01-17 18:20
Same here. 
Getting "provided sha does not match query"

**Comment by sav007** [comment] 2019-01-17 21:53
Are you guys see the same issue `provided sha does not match query`?

**Comment by sosasang** [comment] 2019-01-17 21:54
Yes. After I update the version to 1.0.0-alpha4.

**Comment by davidwinnicki-playster** [comment] 2019-01-17 22:07
Yes I get `provided sha does not match query`

**Comment by sav007** [comment] 2019-01-17 22:43
ok folks #1185 was merged, pls check the snapshot version if it works for you

**Comment by davidwinnicki-playster** [comment] 2019-01-18 13:51
Is this the correct version for the snapshot? 
`com.apollographql.apollo:apollo-gradle-plugin:1.0.1-SNAPSHOT`

**Comment by sav007** [comment] 2019-01-21 02:58
Closing, new release will be next week

**Closed by sav007** 2019-01-21 02:58 UTC

**Comment by sosasang** [comment] 2019-02-02 02:08
Anybody tried 1.0.0-alpha5? I am still facing the same issue

**Comment by Brajendra** [comment] 2019-05-27 07:41
After updating 1.0.1-SNAPSHOT still getting this issue of 400.
