### ISSUE TITLE
The query hash that is generated by apollo-android does not match the query hash that is generated by apollo-link-persisted-queries

### ISSUE THREAD

**Issue by tareq-khandaker-ck** [apollographql/apollo-android#1283] opened 2019-04-30 00:43 UTC
# Problem Description

The query hash that is generated by `apollo-android` does not match the query hash that is generated by `apollo-link-persisted-queries`.

# Investigation

1. I took a query and the query hash generated by `apollo-android` and found that query hash was different from the query hash that `apollo-link-persisted-queries` generates for the same query.

2. I wrote a command-line utility that performed the same steps as `apollo-link-persisted-queries`:

    a. Read a query string.

    b. Perform a `graphql` `parse` on the output of a.

    c. Perform a `graphql` `print` on the output of b.

    d. Compute the SHA256 hash on the output of c.

3. I found that my hash matched the one that `apollo-link-persisted-queries` generates.

4. I looked at the code and saw that https://github.com/apollographql/apollo-android/blob/master/apollo-compiler/src/main/kotlin/com/apollographql/apollo/compiler/OperationTypeSpecBuilder.kt#L58 filters out newlines while https://github.com/apollographql/apollo-link-persisted-queries/blob/master/src/index.ts#L28-L31 does not.

5. I added newline stripping to my utility in 2.

6. I found that my hash now matched the one generated by `apollo-android`.

# Proposed Solutions

There are two possible, mutually-exclusive solutions:

## Either make the change inside `apollo-android`

Change https://github.com/apollographql/apollo-android/blob/master/apollo-compiler/src/main/kotlin/com/apollographql/apollo/compiler/OperationTypeSpecBuilder.kt#L58 to be:

```kotlin
        .initializer("\$S", operation.sourceWithFragments?.sha256())
```

## Or make the change inside `apollo-link-persisted-queries`

Change https://github.com/apollographql/apollo-link-persisted-queries/blob/master/src/index.ts#L30 to be:

```typescript
    .update(print(query).replace(/\n/g, ''))
```

# Related PR

I raised the same concern in `apollo-link-persisted-queries` here: https://github.com/apollographql/apollo-link-persisted-queries/issues/34 .

**Comment by tasomaniac** [comment] 2019-12-25 20:01
@tareq-khandaker-ck can you check if you can reproduce this? Would be awesome to add a failing test case actually.

**Comment by sav007** [comment] 2020-04-13 00:25
Looks like `apollo-link-persisted-queries` is kinda not actively maintained, last commit was 2 years ago. Closing this issue as not really sure if we need to do anything here.

**Closed by sav007** 2020-04-13 00:25 UTC
Labels: Component: compiler
