### ISSUE TITLE
Unable to find documentation for Maven support

### ISSUE THREAD

**Issue by pranay-1995** [apollographql/apollo-android#1213] opened 2019-02-18 11:29 UTC
Hi, I have my project using maven. So I wanted to use maven support for apollo android as well. Is it possible?

**Comment by martinbonnin** [comment] 2019-02-19 13:37
It's not possible at the moment as far as I know. See https://github.com/apollographql/apollo-android/issues/1130

**Comment by sav007** [comment] 2019-05-30 19:31
Closing as it duplicate of #1130

**Closed by sav007** 2019-05-30 19:31 UTC
