### ISSUE TITLE
refetchQueries not executed after mutation

### ISSUE THREAD

**Issue by sp00ne** [apollographql/apollo-android#839] opened 2018-02-28 16:04 UTC
Hi there,

Right now I'm setting a Watcher through
```
private val stateQueryWatcher: ApolloQueryWatcher<HomeQuery.Data> = apolloClient.query(stateQuery).watcher()
```
which is wrapped in an observable. I then call a DialogFragment which upon a confirmation press which then executes a mutation with the addition of
```
...
.refetchQueries(HomeQuery())
```
However, the query is not executed and I don't see anything in the logger. The instance of `ApolloClient` is injected with this setup:
```
    @Provides
    fun provideApolloClient(@Named(AUTH_BUILDER) httpBuilder: OkHttpClient.Builder, resolver: CacheResolver, cacheFactory: SqlNormalizedCacheFactory): ApolloClient {
        val okHttpClient: OkHttpClient = httpBuilder.build()
        val apolloClient = ApolloClient.builder()
            .serverUrl(BASE_URL)
            .normalizedCache(cacheFactory, resolver)
            .defaultResponseFetcher(ApolloResponseFetchers.NETWORK_FIRST)
            .addCustomTypeAdapter(CustomType.INSTANT, ISO8601Adapter())
            .addCustomTypeAdapter(CustomType.UUID, UUIDAdapter())
            .okHttpClient(okHttpClient)

        if (BuildConfig.DEBUG) {
            apolloClient.logger(ApolloLogger())
        }

        return apolloClient.build()
    }
```
The `CacheKeyResolver` is:
```
class CacheResolver : CacheKeyResolver() {
    override fun fromFieldRecordSet(field: ResponseField, recordSet: Map<String, Any>): CacheKey {
        if (BuildConfig.DEBUG) {
            Timber.d("Cache RecordSet: " + recordSet.toString())
        }
        return formatCacheKey(recordSet["id"] as String?)
    }

    override fun fromFieldArguments(field: ResponseField, variables: Operation.Variables): CacheKey {
        if (BuildConfig.DEBUG) {
            Timber.d("Cache FieldArguments; Variables: " + variables.toString())
        }
        return formatCacheKey(field.resolveArgument("id", variables) as String?)
    }

    private fun formatCacheKey(id: String?): CacheKey {
        return if (id == null || id.isEmpty()) {
            CacheKey.NO_KEY
        } else {
            CacheKey.from(id)
        }
    }
}
```
and seems to be working fine, the CacheFactory is taken straight from the examples in the README.
How come the query isn't executed? What am I doing wrong?

**Comment by sav007** [comment] 2018-03-09 23:07
@sp00ne sorry for the delay
Could you please enable http logs in OkHttp client to see if query really not re-fetched?

We have a test for this case: https://github.com/apollographql/apollo-android/blob/master/apollo-integration/src/test/java/com/apollographql/apollo/internal/QueryRefetchTest.java

**Comment by sp00ne** [comment] 2018-03-14 13:15
@sav007 No worries! Thanks for linking the test, I'll get back to you with the logs

**Comment by digitalbuddha** [comment] 2018-05-05 19:53
closing in a week unless followup with logs. Thank you

**Comment by sp00ne** [comment] 2018-05-07 07:31
On it! Gonna collate them somewhat and I'll post it soon :)

**Comment by sav007** [comment] 2018-07-02 21:24
Closing for now due to inactivity, please feel free to reopen if you have any additional info how to reproduce this issue.

**Closed by sav007** 2018-07-02 21:24 UTC
Labels: investigation
