### ISSUE TITLE
Sample app throwing parsing exception

### ISSUE THREAD

**Issue by pranayairan** [apollographql/apollo-android#552] opened 2017-07-07 01:30 UTC
In the sample app when we are querying for github repo pointing to https://githunt-api.herokuapp.com/graphql one of the result in response is "null" this is result number 6, due to this sample app does't work. 

Fix needs to be done on githunt server so that it does't return null. Temporary fix is to fetch only 5 repo by changing FEED_SIZE in GitHunt activity.

**Comment by sav007** [comment] 2017-07-19 21:16
the issue is that schema defines repository as non-null:
```
{
          "kind": "OBJECT",
          "name": "Entry",
          "description": "Information about a GitHub repository submitted to GitHunt",
          "fields": [
            {
              "name": "repository",
              "description": "Information about the repository from GitHub",
              "args": [],
              "type": {
                "kind": "NON_NULL",
                "name": null,
                "ofType": {
                  "kind": "OBJECT",
                  "name": "Repository",
                  "ofType": null
                }
              },
              "isDeprecated": false,
              "deprecationReason": null
            },
```

So we expecting this but in response we are getting null

**Comment by sav007** [comment] 2017-10-04 04:39
I believe we fixed this, closing

**Closed by sav007** 2017-10-04 04:39 UTC
Labels: Priority: Low, Type: Bug
