### ISSUE TITLE
[Code Generation] Union fragment has extra non-nullability check

### ISSUE THREAD

**Issue by minhtule** [apollographql/apollo-android#1389] opened 2019-06-26 00:13 UTC
The GraphQL server has a `shapes` field which returns a list of `Shape`s. In version 1, `Shape` is a union of `Square` and `Circle`. In version 2 of schema, we add a new type `Triangle` to the union so `Shape` is now a union of `Square`, `Circle` and `Triangle`.

The Android client [demo code here](https://github.com/minhtule/helloapollo) is built against the v1 schema and it crashed when the server updates to v2.

This is [the original query](https://github.com/minhtule/helloapollo/blob/master/app/src/main/graphql/com/example/helloapollo/shapes.graphql)
```graphql
query Shapes {
  shapes {
    ...Shape
  }
}

fragment Shape on Shape {
  ...Square
  ...Circle
}

fragment Square on Square {
  name
}

fragment Circle on Circle {
  name
}
```
If we change the query to the following, it works after server upgrade.
```graphql
query Shapes {
  shapes {
    ...Square
    ...Circle
  }
}

fragment Square on Square {
  name
}

fragment Circle on Circle {
  name
}
```

The [gerenated code](https://github.com/minhtule/helloapollo/blob/master/generated/helloapollo/ShapesQuery.java) for the query has a [non-null check](https://github.com/minhtule/helloapollo/blob/master/generated/helloapollo/ShapesQuery.java#L348) on the Shape fragment. This is where the client crashes after the server is upgraded to v2 (with a new type in the `Shape` union).

Is this behavior expected?

**Comment by sav007** [comment] 2019-06-26 17:04
Seems like a bug, will investigate it

**Comment by sav007** [comment] 2019-07-09 04:09
This issue might be closed via this PR: https://github.com/apollographql/apollo-android/pull/1410
And it seems it's a duplicate of https://github.com/apollographql/apollo-android/issues/1344

I'm closing it for now, but feel free to reopen if it's still the case.

**Closed by sav007** 2019-07-09 04:09 UTC
Labels: Type: Bug, Type: compiler
