### ISSUE TITLE
Add HTTP header each query/mutation

### ISSUE THREAD

**Issue by rnitame** [apollographql/apollo-android#672] opened 2017-09-28 10:42 UTC
such as @ Header annotation on Retrofit

**Comment by digitalbuddha** [comment] 2017-09-28 10:46
You can achieve this with okhttp interceptor. Any reason you need the feature to also be in apollo?  https://futurestud.io/tutorials/retrofit-2-manage-request-headers-in-okhttp-interceptor

**Comment by rnitame** [comment] 2017-09-28 11:00
I wanna use with DI containner such as Dagger2. (´・ω・｀)

**Comment by digitalbuddha** [comment] 2017-09-28 11:03
I'm not sure what you mean. Dagger has nothing to do with headers. Closing as this is not a bug report nor do I believe any work needs to be done

**Closed by digitalbuddha** 2017-09-28 11:03 UTC
