### ISSUE TITLE
installApolloCodegen during offline modle 

### ISSUE THREAD

**Issue by jaredsburrows** [apollographql/apollo-android#707] opened 2017-10-28 03:10 UTC
It looks like running `gradlew assembleDebug` --offline prevents `installApolloCodegen` from finishing:

```
  Task ':installApolloCodegen' class path has changed from 035cc40a2b53c91459a2e748443cfbea to 173c47b410cbee6384a7a88020d8c3a4.
Starting process 'command '/Users/<>/.gradle/nodejs/node-v6.7.0-darwin-x64/bin/node''. Working directory: /Users/<>/build/apollo-codegen Command: /Users/<>/.gradle/nodejs/node-v6.7.0-darwin-x64/bin/node /Users/<>/.gradle/nodejs/node-v6.7.0-darwin-x64/lib/node_modules/npm/bin/npm-cli.js install apollo-codegen@0.15.2 --save --save-exact
Successfully started process 'command '/Users/<>/.gradle/nodejs/node-v6.7.0-darwin-x64/bin/node''
<========-----> 68% EXECUTING [3m 5s]
> :installApolloCodegen
```

Does `npm` require internet during this step?

**Comment by marwanad** [comment] 2017-10-28 04:48
Yeah npm requires it, I haven't gotten around to working on a fix yet.

A workaround, in the meantime, could be using Gradle's `startParameter` to remove actions of this task if offline:

```
if (project.getGradle().startParameter.isOffline()) {
 afterEvaluate {
  tasks.installApolloCodegen.deleteAllActions()
 }
}
```

**Comment by hzsweers** [comment] 2017-10-28 13:49
This is a dupe of #579

**Comment by jaredsburrows** [comment] 2017-11-01 21:39
@marwanad Thanks. I will try this! However, if you are running off of a "clean" build then you will eventually need internet access anyways :(

**Comment by jaredsburrows** [comment] 2017-11-01 21:39
Is there someway we can defer to a local `npm` instead of downloading?

**Closed** 2017-11-01 21:42 UTC
