### ISSUE TITLE
Is there any documentation regarding Mutation?

### ISSUE THREAD

**Issue by Reddhi** [apollographql/apollo-android#621] opened 2017-08-11 11:55 UTC
In the sample-android app I could not find any examples on mutation.

**Comment by Oktai15** [comment] 2017-08-11 16:56
Indeed, it is really necessary point for this library. I saw some interesting example this: https://www.youtube.com/watch?v=4cDEfB1xcLc
However, I didn't manage to find this project somewhere to look at code fully. Maybe someone knows where it is located?

**Comment by sav007** [comment] 2017-08-11 19:17
We definitely going to update readme before stable release soon. For now as it's unstable we didn't really put much effort to keep it up-to-date.

Is there any specific question you have in mind, as mutations are almost the same operations as queries.

**Comment by Reddhi** [comment] 2017-08-11 19:28
Can you please share a code snippet showing how a sample mutation can be performed?

**Comment by Reddhi** [comment] 2017-08-11 19:33
@Oktai15 Here's the link for that project: https://github.com/apollographql/apollo-android/tree/master/apollo-sample

You can also check out this blog: https://android.jlelse.eu/hello-apollo-writing-your-first-android-app-with-graphql-d8edabb35a2

**Comment by Oktai15** [comment] 2017-08-11 19:57
@Reddhi Sorry, I can be wrong, but it isn't project which was presented in the link. At least, there you could see many information about сache, also presenter played with button and showed how to cache it correctly... Well, I don't see it on this project.

@sav007 As far as I am concerned, examples about mutation need to show connecting with cache. It will be very useful practice code.

**Comment by sav007** [comment] 2017-08-11 22:02
Absolutely agree and we will add examples into readme.

But for now I can point only to this:

https://github.com/Shopify/mobile-buy-sdk-android/blob/master/MobileBuy/sample/src/apollo/graphql/com/shopify/sample/domain/CheckoutCreate.graphql

https://github.com/Shopify/mobile-buy-sdk-android/blob/master/MobileBuy/sample/src/apollo/java/com/shopify/sample/domain/interactor/RealCheckoutCreateInteractor.java

https://github.com/Shopify/mobile-buy-sdk-android/blob/master/MobileBuy/sample/src/apollo/java/com/shopify/sample/domain/repository/CheckoutRepository.java#L62

**Comment by sav007** [comment] 2017-08-11 22:10
As for the caching  mutations operations are not cached by design (they are always hit network) but the response of mutation updates normalized cache.

**Comment by Oktai15** [comment] 2017-08-12 07:33
@sav007 thank you for links. I noticed that your project has quite good documentation where is mentioned about graphQL: https://github.com/Shopify/mobile-buy-sdk-android#graphclient-

As for me, it would be great, if you had mentioned about it as example in this repo :)

**Comment by sav007** [comment] 2017-08-12 16:36
Our plans to have the same documentation for Apollo

**Comment by sav007** [comment] 2017-08-12 16:38
we have a ticket for that https://github.com/apollographql/apollo-android/issues/297
So will close this one.

**Closed by sav007** 2017-08-12 16:38 UTC
