### ISSUE TITLE
Cache key for generated input object uses default toString method

### ISSUE THREAD

**Issue by wschurman** [apollographql/apollo-android#785] opened 2018-01-11 00:25 UTC
Variable arguments use the toString method to generate their cache key (https://github.com/apollographql/apollo-android/blob/master/apollo-api/src/main/java/com/apollographql/apollo/api/ResponseField.java#L320). 

For primitives types this is fine since these will always be consistent between queries as long as their values are the same. For generated input object types (ones generated by apollo), toString isn't overridden so the default java Object toString is used, resulting in their portion of the cache key being something like `type.TestObject@1afc1`. This is an issue since it doesn't uniquely identify the argument (uses hash code which isn't unique) and may change between queries if the underlying objects change, even if their values are the same.

My proposed fix here is to generate a `toString` method in the `InputTypeSpecBuilder` so that generated input types create correct cache key portions of their field cache key. The generated `toString` method may be able to make use of the marshaller already present in the generated code.

**Comment by sav007** [comment] 2018-01-11 09:07
Are you using input types in the queries? As primary role are to be used in the mutations that are not cacheable by design. And I think we need a better code generation for input type cache keys. 
I think for input type we should generate `cacheKey(): String` method explicitly designed to be used in cache key resolution.

**Comment by wschurman** [comment] 2018-01-11 18:03
> Are you using input types in the queries?

Yep! Makes sense that they were designed to be used with mutations here in apollo.

> I think for input type we should generate cacheKey(): String method explicitly designed to be used in cache key resolution.

That makes sense. We can probably make use of marshaller in the `cacheKey` method, and then make generated input types implement a common interface that can be checked against  in `orderIndependentKeyForVariableArgument` like we do for Map and null.

**Comment by wschurman** [comment] 2018-01-11 22:50
Looking more into this (tried a few implementations), here's what I found:
- Using the marshaller to generate the cache key isn't very clean (causes dependency issues between packages, messy code).
- Can manually codegen a string method (https://gist.github.com/wschurman/76057b261d33d73221357d5b95c82ee2), though this implementation will have the same issue with nested input types, where one input type has other input types within it (http://facebook.github.io/graphql/October2016/#sec-Input-Types).

I think the best route forward is to figure out a way to codegen a cache key serialization method and figure out a way to serialize nested input types into the cache key. Also a note, I didn't test nested input types for field marshalling, but it's probably worth adding a test case for this to ensure it works with apollo.

**Comment by tuncaulubilge** [comment] 2018-03-08 15:58
Should be fixed with: https://github.com/apollographql/apollo-android/pull/840

**Comment by sav007** [comment] 2018-04-04 02:38
Closing due to inactivity

**Closed by sav007** 2018-04-04 02:38 UTC
