### ISSUE TITLE
compileJava fails with `no source files` if the project is 100% kotlin and generateKotlinModels = true

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/apollo-android#1352] opened 2019-06-06 22:30 UTC
> Task :compileJava FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':compileJava'.
    > no source files

This comes from there: https://github.com/apollographql/apollo-android/blob/b327bc79a94e5a1c7ebef5e42554dc86a12c1225/apollo-gradle-plugin/src/main/groovy/com/apollographql/apollo/gradle/ApolloPlugin.groovy#L105

If the directory is empty, the java compiler does not complain but in that case it contains kotlin files that make javac not happy.

**Comment by alexxxdev** [comment] 2019-06-17 01:54
now it causes problems with `compile%name%Kotlin`
for any value of `generateKotlinModels`
project is 100% kotlin

**Comment by sav007** [comment] 2019-06-17 03:20
Just to make sure, you tried the latest snapshot version? Could you please provide a log with the stacktrace for you build?

**Comment by sav007** [comment] 2019-06-17 03:26
Just tried on my sample app (pure Kotlin) couldn't reproduce any errors

**Comment by alexxxdev** [comment] 2019-06-17 03:33
@sav007 in logs only https://gist.github.com/alexxxdev/3a2581b9da277868ef99015d535394c6
and errors in unresolved classes, which do not generate

**Comment by alexxxdev** [comment] 2019-06-17 04:41
also i did 
`git clone https://github.com/apollographql/apollo-android.git`
and
`./gradlew clean build connectedCheck -x checkstyleTest --stacktrace --max-workers=2 -x apollo-integration:build -x apollo-integration:connectedCheck`
I getting tighter error https://gist.github.com/alexxxdev/f12fee47cad255b4ab0c32bf24cc1e0e

**Comment by martinbonnin** [comment] 2019-06-17 07:30
@alexxxdev I can reproduce with `./gradlew :apollo-kotlin-sample:compileDebugKotlin` from apollo-android master, I'm looking into it.

**Comment by martinbonnin** [comment] 2019-06-17 08:00
This seems to be a side effect of `afterEvaluate` in the android case. It looks like `registerJavaGeneratingTask` is not picking up the codegen tasks and it works again if I remove the `afterEvaluate`. @sav007 feel free to revert https://github.com/apollographql/apollo-android/pull/1353 for now as it might take a bit of time to investigate.

**Comment by martinbonnin** [comment] 2019-06-17 23:32
I have been looking into that a bit today. Somehow, `compileDebugKotlin` does not depend on `generateDebugSources` if `afterEvaluate` is used. Not sure yet why.

**Comment by sav007** [comment] 2019-06-18 17:30
As for workaround change the order of applied plugins, at least it helped to resolved issues with our kotlin sample project

https://github.com/apollographql/apollo-android/pull/1374/commits/8882237cfa40e07955dac83e5f88b30c5f776d88

**Comment by martinbonnin** [comment] 2019-06-18 23:00
Ah yes put the apollo plugin in sandwich between com.android.application and kotlin-android. I guess that works because `afterEvaluate` callbacks are made in the same order as they are registered and the one from the kotlin plugin [there](https://github.com/JetBrains/kotlin/blob/8372e917ef99c6a5825513a4184b9b010d1aa9f4/libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/plugin/KotlinPlugin.kt#L777) is called after the apollo one.

One solution would be to run `addApolloTasks` immediately if we detect that an android plugin is applied and run from `afterEvaluate` in the non-android case. It adds even more complexity to the plugin but maybe we don't care that much at that point.

**Comment by sav007** [comment] 2019-06-26 17:08
@martinbonnin do you think this issue https://github.com/apollographql/apollo-android/issues/1384 is caused  by the changes to `afterEvaluate ` as well?

**Comment by martinbonnin** [comment] 2019-06-27 07:35
@sav007 It's hard to tell 100% without being able to reproduce but I wouldn't be too surprised. I'll make a PR to try the suggestion above (add immediately for android projects and afterEvaluate for non-android).

**Comment by sav007** [comment] 2019-07-09 04:34
I believe it was fixed, closing for now.

**Closed by sav007** 2019-07-09 04:34 UTC

**Comment by ZacSweers** [comment] 2019-11-11 18:16
Believe this is an issue with AGP, filed https://issuetracker.google.com/issues/144249620

**Comment by martinbonnin** [comment] 2019-11-11 19:37
I filed this for non-Android projects and it was fixed here https://github.com/apollographql/apollo-android/commit/a1cd963f632e2a5d333b9d34e90107b9b5e6733f. But I'm not sure what the status is on Android projects with the current project.

The incubating plugin shouldn't have this problem neither on android nor non-android. On Android, it doesn't call registerJavaGeneratingTask(): https://github.com/apollographql/apollo-android/blob/fc37c15827e0fa8d11d212ba8e69a875c88113d7/apollo-gradle-plugin-incubating/src/main/kotlin/com/apollographql/apollo/gradle/internal/AndroidTaskConfigurator.kt#L56

**Comment by ZacSweers** [comment] 2019-11-11 19:42
What’s the reason for using that manual approach over the formal API?
(Aside from this bug). Seems like that might result in weird behavior if a
code gen plugin is doing something different than the rest that AGP doesn’t
expect

**Comment by martinbonnin** [comment] 2019-11-11 20:01
Mainly this bug + the fact that it's called `registerJavaGeneratingSources` and not `registerKotlinGeneratingSources` + the hope to make it lazy at some point.

**Comment by ZacSweers** [comment] 2019-11-11 20:03
The name is confusing, but my understanding is this is intended for both
Java and Kotlin sources.

**Comment by martinbonnin** [comment] 2019-11-11 20:06
Slightly related but I found out recently that calling `registerJavaGeneratingTask` too late (from project.afterEvaluate {}) doesn't add the java sources to the KotlinCompileTask. 

All in all this area seems tricky and I'm hoping that by doing things manually, at least we'll gain some knowledge about what's exactly going on.

**Comment by ZacSweers** [comment] 2019-11-11 20:07
Why not file bugs on AGP instead? Seems like this had slipped under their
radar so far due to plugin authors not reporting it :)

**Comment by martinbonnin** [comment] 2019-11-11 20:30
Here you go :) https://issuetracker.google.com/issues/144297372 
Apollo-android uses AGP 3.4.2 but I just verified it also happens on 3.5.2
