### ISSUE TITLE
[dev-3.x] Subscriptions failing on iOS (freezing error)

### ISSUE THREAD

**Issue by martinraison** [apollographql/apollo-android#3127] opened 2021-05-26 12:58 UTC
**Summary**
I'm not able to get subscriptions to work on iOS with 3.x (Android works fine), so I'm posting a minimal repro in case it can help.

**Version**
3.0-dev10

**Description**
Thanks for the great work on this library! I'm very interested in using Kotlin multiplatform with GraphQL moving forward, so I've been testing the dev-3.x branch out of curiosity. I'm not able to get subscriptions to work on iOS (Android is working fine). I'm getting either "freezing has failed" or "IncorrectDereferenceException" errors, originating from the library code.

I understand 3.x is not ready yet but I wanted to put this issue on your radar so I made a minimal repro here: https://github.com/martinraison/kmm-repro-ios-subscription-crash

The repro is using `https://apollo-fullstack-tutorial.herokuapp.com/graphql` as a server, which is not always reliable (but the demo should work on Android so you can easily see if the server is down)

Note: iOS requires a bit of bridging code in order to be able to consume `Flow<T>` from Swift. I used the approach explained here, with a `FlowWrapper`: https://touchlab.co/kotlin-coroutines-rxswift/

I hope it can help you. Let me know if you need anything else!

**Comment by martinbonnin** [comment] 2021-05-26 13:10
Thank you for providing a reproducer, that helps a ton 😊 ! Will look into it!

**Comment by martinbonnin** [comment] 2021-05-27 18:37
Turns out the `coroutines-native-mt` seem to freeze the channel and removing the `ensureNeverFrozen` did the job.

**Comment by martinraison** [comment] 2021-05-29 14:27
I can confirm the fix, I was able to get subscriptions to work on iOS. Thanks a lot for the help!

Note: I still occasionally get a failure with the stacktrace below, but I haven't been able to repro consistently. If I can find a better repro I may open a separate issue in the future.

```
cancelling trip 1
    at 0   shared                              0x000000010c693eee kfun:kotlin.Exception#<init>(kotlin.String?;kotlin.Throwable?){} + 126 (/Users/teamcity1/teamcity_work/290aee0e088a1666/runtime/src/main/kotlin/kotlin/Exceptions.kt:25:63)
    at 1   shared                              0x000000010c69415e kfun:kotlin.RuntimeException#<init>(kotlin.String?;kotlin.Throwable?){} + 126 (/Users/teamcity1/teamcity_work/290aee0e088a1666/runtime/src/main/kotlin/kotlin/Exceptions.kt:36:63)
    at 2   shared                              0x000000010c8c653e kfun:com.apollographql.apollo3.api.exception.ApolloException#<init>(kotlin.String?;kotlin.Throwable?){} + 126 (/Users/runner/work/apollo-android/apollo-android/apollo-api/src/commonMain/kotlin/com/apollographql/apollo3/api/exception/Exceptions.kt:6:81)
    at 3   shared                              0x000000010c8c681e kfun:com.apollographql.apollo3.api.exception.ApolloNetworkException#<init>(kotlin.String?;kotlin.Throwable?){} + 126 (/Users/runner/work/apollo-android/apollo-android/apollo-api/src/commonMain/kotlin/com/apollographql/apollo3/api/exception/Exceptions.kt:11:83)
    at 4   shared                              0x000000010c9f3774 kfun:com.apollographql.apollo3.network.ws.ApolloWebSocketNetworkTransport.$createConnectionCOROUTINE$14.invokeSuspend#internal + 2884 (/Users/runner/work/apollo-android/apollo-android/apollo-runtime-kotlin/src/commonMain/kotlin/com/apollographql/apollo3/network/ws/ApolloWebSocketNetworkTransport.kt:210:13)
    at 5   shared                              0x000000010c6bdc20 kfun:kotlin.coroutines.native.internal.BaseContinuationImpl#resumeWith(kotlin.Result<kotlin.Any?>){} + 800 (/Users/teamcity1/teamcity_work/290aee0e088a1666/runtime/src/main/kotlin/kotlin/coroutines/ContinuationImpl.kt:30:39)
    at 6   shared                              0x000000010c9a2c70 kfun:kotlinx.coroutines.DispatchedTask#run(){} + 2880 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/internal/DispatchedTask.kt:106:71)
    at 7   shared                              0x000000010c9d0eaa kfun:kotlinx.coroutines.DarwinMainDispatcher.dispatch$lambda-0#internal + 90 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/nativeDarwin/src/Dispatchers.kt:35:19)
    at 8   shared                              0x000000010c9d1200 kfun:kotlinx.coroutines.DarwinMainDispatcher.$dispatch$lambda-0$FUNCTION_REFERENCE$43.invoke#internal + 64 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/nativeDarwin/src/Dispatchers.kt:34:51)
    at 9   shared                              0x000000010c9d1310 kfun:kotlinx.coroutines.DarwinMainDispatcher.$dispatch$lambda-0$FUNCTION_REFERENCE$43.$<bridge-UNN>invoke(){}#internal + 64 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/nativeDarwin/src/Dispatchers.kt:34:51)
    at 10  shared                              0x000000010c9d2429 _6f72672e6a6574627261696e732e6b6f746c696e783a6b6f746c696e782d636f726f7574696e65732d636f7265_knbridge8 + 185 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/nativeDarwin/src/Dispatchers.kt:34:51)
    at 11  libdispatch.dylib                   0x00007fff2010670d _dispatch_call_block_and_release + 12
    at 12  libdispatch.dylib                   0x00007fff201078df _dispatch_client_callout + 8
    at 13  libdispatch.dylib                   0x00007fff20114a27 _dispatch_main_queue_callback_4CF + 1045
    at 14  CoreFoundation                      0x00007fff203908f8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
    at 15  CoreFoundation                      0x00007fff2038b169 __CFRunLoopRun + 2781
    at 16  CoreFoundation                      0x00007fff2038a1a7 CFRunLoopRunSpecific + 567
    at 17  GraphicsServices                    0x00007fff2b874d85 GSEventRunModal + 139
    at 18  UIKitCore                           0x00007fff246c14df -[UIApplication _run] + 912
    at 19  UIKitCore                           0x00007fff246c639c UIApplicationMain + 101
    at 20  SwiftUI                             0x00007fff567a8c36 $s7SwiftUI17KitRendererCommon33_ACC2C5639A7D76F611E170E831FCA491LLys5NeverOyXlXpFAESpySpys4Int8VGSgGXEfU_ + 119
    at 21  SwiftUI                             0x00007fff567a8bbd $s7SwiftUI6runAppys5NeverOxAA0D0RzlF + 143
    at 22  SwiftUI                             0x00007fff562e5384 $s7SwiftUI3AppPAAE4mainyyFZ + 61
    at 23  iosApp                              0x000000010c526131 $s6iosApp6iOSAppV5$mainyyFZ + 33 (/Users/martinraison/sandbox/kmm-repro-ios-subscription-crash/iosApp/iosApp/iOSApp.swift:<unknown>)
    at 24  iosApp                              0x000000010c5261b4 main + 20
    at 25  libdyld.dylib                       0x00007fff2025abbd start + 1
    at 26  ???                                 0x0000000000000001 0x0 + 1
Caused by: kotlin.native.concurrent.FreezingException: freezing of RemoveReceiveOnCancel[ReceiveElement@2b13ac8[receiveMode=0]] has failed, first blocker is ArrayChannel@2b06148{ReceiveQueued}(buffer:capacity=64,size=0)
    at 0   shared                              0x000000010c69a96f kfun:kotlin.Throwable#<init>(kotlin.String?){} + 95 (/Users/teamcity1/teamcity_work/290aee0e088a1666/runtime/src/main/kotlin/kotlin/Throwable.kt:23:37)
    at 1   shared                              0x000000010c693e3d kfun:kotlin.Exception#<init>(kotlin.String?){} + 93 (/Users/teamcity1/teamcity_work/290aee0e088a1666/runtime/src/main/kotlin/kotlin/Exceptions.kt:23:44)
    at 2   shared                              0x000000010c6940ad kfun:kotlin.RuntimeException#<init>(kotlin.String?){} + 93 (/Users/teamcity1/teamcity_work/290aee0e088a1666/runtime/src/main/kotlin/kotlin/Exceptions.kt:34:44)
    at 3   shared                              0x000000010c6ca935 kfun:kotlin.native.concurrent.FreezingException#<init>(kotlin.Any;kotlin.Any){} + 645 (/Users/teamcity1/teamcity_work/290aee0e088a1666/runtime/src/main/kotlin/kotlin/native/concurrent/Freezing.kt:15:9)
    at 4   shared                              0x000000010c6cc009 ThrowFreezingException + 233 (/Users/teamcity1/teamcity_work/290aee0e088a1666/runtime/src/main/kotlin/kotlin/native/concurrent/Internal.kt:88:15)
    at 5   shared                              0x000000010c82323b FreezeSubgraph + 4939
    at 6   shared                              0x000000010c84fedb Kotlin_Worker_freezeInternal + 27
    at 7   shared                              0x000000010c6caa60 kfun:kotlin.native.concurrent#freeze__at__0:0(){0§<kotlin.Any?>}0:0 + 64 (/Users/teamcity1/teamcity_work/290aee0e088a1666/runtime/src/main/kotlin/kotlin/native/concurrent/Freezing.kt:33:5)
    at 8   shared                              0x000000010c90e75f kfun:kotlinx.coroutines.CancellableContinuationImpl#invokeOnCancellation(kotlin.Function1<kotlin.Throwable?,kotlin.Unit>){} + 1279 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/CancellableContinuationImpl.kt:395:10)
    at 9   shared                              0x000000010c94efe8 kfun:kotlinx.coroutines.channels.AbstractChannel.removeReceiveOnCancel#internal + 424 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/channels/AbstractChannel.kt:839:14)
    at 10  shared                              0x000000010c94aff9 kfun:kotlinx.coroutines.channels.AbstractChannel.receiveSuspend#internal + 1273 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/channels/AbstractChannel.kt:619:17)
    at 11  shared                              0x000000010c94aa5c kfun:kotlinx.coroutines.channels.AbstractChannel#receive(){}1:0 + 476 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/channels/AbstractChannel.kt:609:16)
    at 12  shared                              0x000000010c9e30bc kfun:com.apollographql.apollo3.network.ws.WebSocketConnectionImpl.receive#internal + 236 (/Users/runner/work/apollo-android/apollo-android/apollo-runtime-kotlin/src/appleMain/kotlin/com/apollographql/apollo3/network/ws/NSURLSessionWebSocketEngine.kt:123:27)
    at 13  shared                              0x000000010c9fbbea kfun:com.apollographql.apollo3.network.ws.ApolloWebSocketNetworkTransport.$createConnection$lambda-5COROUTINE$20.invokeSuspend#internal + 1594 (/Users/runner/work/apollo-android/apollo-android/apollo-runtime-kotlin/src/commonMain/kotlin/com/apollographql/apollo3/network/ws/ApolloWebSocketNetworkTransport.kt:196:45)
    at 14  shared                              0x000000010c9fc56b kfun:com.apollographql.apollo3.network.ws.ApolloWebSocketNetworkTransport.$createConnection$lambda-5COROUTINE$20.invoke#internal + 331 (/Users/runner/work/apollo-android/apollo-android/apollo-runtime-kotlin/src/commonMain/kotlin/com/apollographql/apollo3/network/ws/ApolloWebSocketNetworkTransport.kt:193:51)
    at 15  shared                              0x000000010c9b1705 kfun:kotlinx.coroutines.intrinsics#startUndispatchedOrReturnIgnoreTimeout__at__kotlinx.coroutines.internal.ScopeCoroutine<0:0>(0:1;kotlin.coroutines.SuspendFunction1<0:1,0:0>){0§<kotlin.Any?>;1§<kotlin.Any?>}kotlin.Any? + 981 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/intrinsics/Undispatched.kt:102:2)
    at 16  shared                              0x000000010c93e6a5 kfun:kotlinx.coroutines.setupTimeout#internal + 805 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/Timeout.kt:148:22)
    at 17  shared                              0x000000010c93db51 kfun:kotlinx.coroutines#withTimeout(kotlin.Long;kotlin.coroutines.SuspendFunction1<kotlinx.coroutines.CoroutineScope,0:0>){0§<kotlin.Any?>}0:0 + 369 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/Timeout.kt:44:9)
    at 18  shared                              0x000000010c9f35c2 kfun:com.apollographql.apollo3.network.ws.ApolloWebSocketNetworkTransport.$createConnectionCOROUTINE$14.invokeSuspend#internal + 2450 (/Users/runner/work/apollo-android/apollo-android/apollo-runtime-kotlin/src/commonMain/kotlin/com/apollographql/apollo3/network/ws/ApolloWebSocketNetworkTransport.kt:193:7)
    at 19  shared                              0x000000010c6bdc20 kfun:kotlin.coroutines.native.internal.BaseContinuationImpl#resumeWith(kotlin.Result<kotlin.Any?>){} + 800 (/Users/teamcity1/teamcity_work/290aee0e088a1666/runtime/src/main/kotlin/kotlin/coroutines/ContinuationImpl.kt:30:39)
    at 20  shared                              0x000000010c9a2c70 kfun:kotlinx.coroutines.DispatchedTask#run(){} + 2880 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/common/src/internal/DispatchedTask.kt:106:71)
    at 21  shared                              0x000000010c9d0eaa kfun:kotlinx.coroutines.DarwinMainDispatcher.dispatch$lambda-0#internal + 90 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/nativeDarwin/src/Dispatchers.kt:35:19)
    at 22  shared                              0x000000010c9d1200 kfun:kotlinx.coroutines.DarwinMainDispatcher.$dispatch$lambda-0$FUNCTION_REFERENCE$43.invoke#internal + 64 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/nativeDarwin/src/Dispatchers.kt:34:51)
    at 23  shared                              0x000000010c9d1310 kfun:kotlinx.coroutines.DarwinMainDispatcher.$dispatch$lambda-0$FUNCTION_REFERENCE$43.$<bridge-UNN>invoke(){}#internal + 64 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/nativeDarwin/src/Dispatchers.kt:34:51)
    at 24  shared                              0x000000010c9d2429 _6f72672e6a6574627261696e732e6b6f746c696e783a6b6f746c696e782d636f726f7574696e65732d636f7265_knbridge8 + 185 (/opt/buildAgent/work/44ec6e850d5c63f0/kotlinx-coroutines-core/nativeDarwin/src/Dispatchers.kt:34:51)
    at 25  libdispatch.dylib                   0x00007fff2010670d _dispatch_call_block_and_release + 12
    at 26  libdispatch.dylib                   0x00007fff201078df _dispatch_client_callout + 8
    at 27  libdispatch.dylib                   0x00007fff20114a27 _dispatch_main_queue_callback_4CF + 1045
    at 28  CoreFoundation                      0x00007fff203908f8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
    at 29  CoreFoundation                      0x00007fff2038b169 __CFRunLoopRun + 2781
```

**Comment by martinbonnin** [comment] 2021-05-29 14:34
Thanks for the update. Let's keep this issue open for now. It's weird because the stacktrace look very similar... I'll double check the code to see if there are other places where we call `ensureNotFrozen` on a `Channel`

**Comment by martinraison** [comment] 2021-05-29 19:55
Now that I think about it, I've seen a couple of cases where gradle/xcodebuild picks up an old version of the shared lib when compiling, and if I try again the new version is used. So this one could be a red herring.

**Comment by martinbonnin** [comment] 2021-06-02 09:54
I'm closing it for now. Do not hesitate to leave a message if this happens again and I'll reopen!

**Closed by martinbonnin** 2021-06-02 09:54 UTC
Labels: Type: Bug
