### ISSUE TITLE
Mapping an interface with both fields and inline fragments returns `null` if the object isn't an instance of any fragments

### ISSUE THREAD

**Issue by benkuhn** [apollographql/apollo-android#955] opened 2018-06-16 12:02 UTC
Example:

```
# schema.graphql
interface Fruit { weight: Int! }
type Apple implements Fruit { redness: Float! }
type Banana implements Fruit { curvature: Float! }
type Starfruit implements Fruit { numPoints: Int! }
type Query {
    inventory: [Fruit]!
}
```

```
# FruitQuery.graphql
query FruitQuery {
    inventory {
        weight
        ...on Apple {
            redness
        }
        ...on Banana {
            curvature
        }
        # no query for Starfruit but I still expect to
        # see the weight of any starfruit in the inventory
    }
}
```

The generated mapping code for `Inventory.Mapper.map` will look something like:

```
public Inventory map(reader) {
    final AsApple asApple = reader.readConditional(...)
    if (asApple != null) {
        return asApple;
    }
    // same with asBanana
    return null
}
```

At the end, there should be a line that maps an object with *only* the `weight` field into a concrete subtype of `Inventory`. Otherwise, a response of `{"__typename": "Starfruit", "weight": 1}` will be mapped to `null`.

(Side note: I haven't tested this exact example because I got stuck in Gradle sync hell when I tried to make a minimal repro. In a closed-source codebase on v0.5.0 I have an example that is, AFAICT, exactly the same but with more fragments and the names changed, but it's possible I've missed an essential feature. Happy to do further debugging if someone with a working build can't reproduce this.)

**Comment by josephyanks** [comment] 2018-06-22 19:40
+1, we are experiencing this same issue. This also apparently doesn't affect the iOS variant of our app. We have a workaround where we specify every single type as a different fragment, but it should be able to fall back on the base type. Can provide code examples as well if need be.

**Comment by benkuhn** [comment] 2018-06-24 16:52
Ah, here's an example of the bug in the test suite:

https://github.com/apollographql/apollo-android/blob/master/apollo-compiler/src/test/graphql/com/example/fragment_with_inline_fragment/fragment/HeroDetails.java#L76

As you can see, the mapper will return null unless the returned object has a typename of `Droid`, even though the query asks for the `name` even of non-Droid characters.

**Comment by benkuhn** [comment] 2018-06-25 10:34
@sav007 would love any feedback on the PR!

**Comment by sav007** [comment] 2018-06-25 20:33
The issue is not inside the android compiler but (in my opinion) inside the apollo-codegen. @martijnwalraven could you pls give your input here? There are 2 solutions one is depicted in above to generate some  base class  or if field requested on generic interface then we need to include all possible sub-types in inline fragments section in IR.

**Comment by benkuhn** [comment] 2018-06-25 20:44
@sav007 If you did the second solution (add all possible subtypes as inline fragments) wouldn't it still break old versions if the server later added a new interface subtype?

**Comment by martijnwalraven** [comment] 2018-06-25 20:58
@sav007 I don't know exactly what the generated code looks like on Android, but it may be a limitation of the legacy IR you're using. On other platforms, we now use a different representation that relies on the notion of a type case: https://github.com/apollographql/apollo-codegen/blob/master/packages/apollo-codegen-core/src/compiler/visitors/typeCase.ts

A type case has a default case that could be used as a base class.

**Comment by martijnwalraven** [comment] 2018-06-25 21:02
I don't remember exactly how this maps to the legacy IR and what the limitations are, but it seems we do use type case to generate it: https://github.com/apollographql/apollo-codegen/blob/27503ba32112077097e6a996b6c03e971dc4a2a0/packages/apollo-codegen-core/src/compiler/legacyIR.ts#L164

**Comment by sav007** [comment] 2018-06-25 21:07
Hm @martijnwalraven ,
```
query TestQuery {
  hero {
    name
    ... on Human {
      height
    }
  }
}
```

Generates this IR:
```
{
	"operations": [
		{
			"filePath": "src/test/graphql/com/example/simple_inline_fragment/TestOperation.graphql",
			"operationName": "TestQuery",
			"operationType": "query",
			"rootType": "Query",
			"variables": [],
			"source": "query TestQuery {\n  hero {\n    __typename\n    name\n    ... on Human {\n      height\n    }\n  }\n}",
			"fields": [
				{
					"responseName": "hero",
					"fieldName": "hero",
					"type": "Character",
					"isConditional": false,
					"isDeprecated": false,
					"deprecationReason": null,
					"fields": [
						{
							"responseName": "__typename",
							"fieldName": "__typename",
							"type": "String!",
							"isConditional": false
						},
						{
							"responseName": "name",
							"fieldName": "name",
							"type": "String!",
							"isConditional": false,
							"description": "The name of the character",
							"isDeprecated": false,
							"deprecationReason": null
						}
					],
					"fragmentSpreads": [],
					"inlineFragments": [
						{
							"typeCondition": "Human",
							"possibleTypes": [
								"Human"
							],
							"fields": [
								{
									"responseName": "__typename",
									"fieldName": "__typename",
									"type": "String!",
									"isConditional": false
								},
								{
									"responseName": "name",
									"fieldName": "name",
									"type": "String!",
									"isConditional": false,
									"description": "What this human calls themselves",
									"isDeprecated": false,
									"deprecationReason": null
								},
								{
									"responseName": "height",
									"fieldName": "height",
									"type": "Float",
									"isConditional": false,
									"description": "Height in the preferred unit, default is meters",
									"isDeprecated": false,
									"deprecationReason": null
								}
							],
							"fragmentSpreads": []
						}
					]
				}
			],
			"fragmentSpreads": [],
			"inlineFragments": [],
			"fragmentsReferenced": [],
			"sourceWithFragments": "query TestQuery {\n  hero {\n    __typename\n    name\n    ... on Human {\n      height\n    }\n  }\n}",
			"operationId": "72e4640d4c42efcd95217731e2c6cc419f2598953d8cb66813870c0e3ce11f95"
		}
	],
	"fragments": [],
	"typesUsed": []
}
```

As you can see that only `Human` was included as inline fragment (no Droid type). Or am I missing something?

**Comment by martijnwalraven** [comment] 2018-06-25 21:11
That seems like expected behavior to me? There is no inline fragment for a Droid, so nothing specific to that type. You don't want an inline fragment for every possible type if you're not selecting from it. That is what the base case is for.

**Comment by martijnwalraven** [comment] 2018-06-25 21:14
I know people with dozens of implementations of an interface, and generating all possible types every time you select from that interface would lead to way too much code.

**Comment by martijnwalraven** [comment] 2018-06-25 21:15
For the above query, I would expect both `TestQuery.Hero` (with `name`) and `TestQuery.Hero.AsHuman` (with `name` and `height`) to be generated, but no `AsDroid`.

**Comment by sav007** [comment] 2018-06-26 14:04
We are generating `Hero` as an interface, but I think what we need is to make it generated as a class instead and `AsDroid ` will be inherited from it.

**Comment by benkuhn** [comment] 2018-06-27 10:45
Hmm, I'm afraid that's a much deeper change to the codegen that I probably don't know how to do (because it would require extending SchemaTypeSpecBuilder to take an optional superclass and change the generated code for nearly every method if the superclass is present). Is someone with more apollo-compiler experience able to take this over?

**Comment by sav007** [comment] 2018-06-27 14:37
no worries I will take a look at it

**Closed** 2018-07-02 20:41 UTC
Labels: Status: In Progress
