### ISSUE TITLE
annotation type not applicable to this kind of declaration

### ISSUE THREAD

**Issue by FernandoH-G** [apollographql/apollo-android#2246] opened 2020-05-05 07:04 UTC
**Summary**
While running ./gradlew generateApolloSources the generated files for one of my mutations seems to a type class incorrectly.  It builds with ./gradlew succesfully, but when Making Project it fails.
Build fails with error: annotation type not applicable to this kind of declaration
**Description**
I build with four queries.
```
mutation SignUpBarber($input: NewBarber!) {
    signUpBarber(input: $input) {
        response
        error
    }
}

query GetAllBarbers{
    getAllBarbers{
        barberID
        firstName
        lastName
    }
}

mutation RefreshToken($input: RefreshTokenInput!) {
    refreshToken(input: $input) {
        response
        error
    }
}

mutation LoginBarber($input: Login!) {
    login(input: $input) {
        response
        error
    }
}
```
The mutation that throws the error is LoginBarber.
RefreshToken mutationis quite similar, but it does not throw the error in question.

The error lies in this code 
```
 public LoginBarberMutation(com.snipsnap.android.barbershop.type. @NotNull Login input) {
    Utils.checkNotNull(input, "input == null");
    variables = new LoginBarberMutation.Variables(input);
  }
```
While the mutation for RefreshToken looks like this and produces no error
```
 public RefreshTokenMutation(@NotNull RefreshTokenInput input) {
    Utils.checkNotNull(input, "input == null");
    variables = new RefreshTokenMutation.Variables(input);
  }
```

public LoginBarberMutation(com.snipsnap.android.barbershop.type. @NotNull Login input)
throws the annotation type not applicable to this kind of declaration error.

**Version**
Provide a version of library on which the problem occurred.

Android Studio 3.6.3
classpath("com.apollographql.apollo:apollo-gradle-plugin:1.3.3")
implementation("com.apollographql.apollo:apollo-runtime:1.3.3")

Let me know if y'all need additional information. Ty in advanced!

**Comment by martinbonnin** [comment] 2020-05-05 16:45
Can you try with version`2.0.1` to make sure it's not already fixed in the latest version?

It looks like there might be a name clash between the `Login` input and potentially another `Login` class in the same file or package. Are there other `Login` classes in your project?

**Comment by FernandoH-G** [comment] 2020-05-05 21:34
I have upgraded to `2.0.1`
I have deleted the generated files and initiated a shift+shift search for files matching Login.
The result is attached as an image.
![login_error](https://user-images.githubusercontent.com/23583398/81118163-4254ed00-8edd-11ea-92fd-f899d713cfbf.png)
This was before I ran `./gradlew generateApolloSources ` to make sure there were no other Login classes. However, the same errors with Login persist.

**Comment by FernandoH-G** [comment] 2020-05-06 03:17
So I just went ahead and renamed the input to UserLogin, downloaded the new schema, and generated apollo sources, and everything seems to be working as expected.

Thanks for the assistance!

I don't know if I should close since it's not like this bug is fixed. Maybe it's common sense not to name the input and mutation the same? I'll leave that up to y'all!

**Comment by martinbonnin** [comment] 2020-05-06 23:47
Thanks for the follow up. That does sound weird indeed. Let's keep this open for the time being.

**Comment by martinbonnin** [comment] 2020-05-11 14:13
It turns out a field of the mutation is called `login` and that will generate an inner class named `Login`:

``` 
mutation LoginBarber($input: Login!) {
    login(input: $input) { // This here will create a `Login` inner class that will clash with the input type
        response
        error
    }
}
```

I tried to reproduce by tweaking the schema but somehow it generates working code:

https://github.com/martinbonnin/apollo-android/blob/bug-2246-annotation-in-package-name/apollo-compiler/src/test/graphql/com/snipsnap/android/barbershop/LoginBarberMutation.java#L61

**Comment by FernandoH-G** [comment] 2020-05-12 07:33
Was there an additional mistake on my side then?
I was under the impression that the input type should not be named the same as the field. But, from your code, it looks like that will still generate working code.

**Comment by martinbonnin** [comment] 2020-05-12 08:00
Javapoet is smart enough to use qualified names to avoid name clashes so it "should" work. But that space before the annotation looks a bit suspicious...

**Comment by LobnaMazhar** [comment] 2020-05-12 15:01
The same bug happened with me when I added "androidx.navigation:navigation-safe-args-gradle-plugin" classpath to the project gradle file

**Comment by martinbonnin** [comment] 2020-05-12 15:22
@LobnaMazhar good catch! Looks like it happens with JavaPoet `1.12.1` (apollo-android depends on JavaPoet `1.9.0`). I'll investigate a bit more.

**Comment by rcosteira79** [comment] 2021-02-08 13:20
Hello :) Just ran into this while adding the "androidx.navigation:navigation-safe-args-gradle-plugin" classpath to my project. Do you know if there's any way to work around it? 

Thanks!

**Comment by martinbonnin** [comment] 2021-02-08 14:11
@rcosteira79 switching to Kotlin models (`generateKotlinModels.set(true)`) will certainly be the easiest workaround.

**Comment by martinbonnin** [comment] 2021-10-05 13:19
Reproducer on 2.x https://gist.github.com/martinbonnin/dc40d65595921e692463a200ff9bbe3c

Test case on 3.x: https://github.com/apollographql/apollo-android/pull/3390

Closing as it doesn't happen in 3.x anymore.

**Closed by martinbonnin** 2021-10-05 13:19 UTC
Labels: Component: compiler, Type: Bug
