### ISSUE TITLE
Add option to skip the `.fragments` field

### ISSUE THREAD

**Issue by heavyauto** [apollographql/apollo-android#2993] opened 2021-03-11 14:45 UTC
Hello, I have a question about the Fragment. 
For example, I have a query Q which contains a field is Fragment A, then Fragment A contains a field Fragment B, B contains Fragment C. So in the generated Kotlin class for the Query Q, in order to access the value in the C. I need to do something like this 
```
Q.A?.fragments?.B?.fragments?.C?.fragments?.fieldxxx
```
is there any way to avoid the nested `fragments` list in each layer? 

Thanks!

**Comment by martinbonnin** [comment] 2021-03-11 15:04
Hi 👋  ! 

There's no way to avoid the `fragments` intermediate at the moment but this is something we're thinking about. Is there a specific thing you'd like to see? 

```
// removing the `fragments` is relatively easy to implement but possibly exposes to name clashes if a field has the same name as a fragment
Q.A?.B?.C?.fieldxxx
// bypassing all the fragments to reach the leaf field is way harder due to the fact that ther can be multiple fragments, etc......
Q?.fieldxxx
```

**Comment by heavyauto** [comment] 2021-03-11 15:25
Thanks @martinbonnin for your prompt reply. Also, Big thanks to you and your team for great works on Apollo library. 👍 

`Q.A?.B?.C?.fieldxxx` is the way we'd like to have.

Recently we are trying to introduce the Apollo library to our Android project. The main reason we want to migrate to Apollo library is we want to reuse the `Fragment` classes in different queries. But the biggest downside of the Apollo library I have seen so far is this nested fragments class. 

We are considering to use Apollo models directly in the ViewModel layer. (because otherwise we will have to do many 1-1 mappings to Domain models). But because of this nested fragment class, it make the field access code looks kind of "ugly" in the ViewModel layer and also the data bindings. 

I heard you are working the V3.0. do you have plan to remove it V3.0?

**Comment by martinbonnin** [comment] 2021-03-11 15:36
Thanks for the context! I can definitely see how the `.fragments` makes everything more verbose. 

V3.0 will indeed try to address this. It has a lot of moving parts (see the [ROADMAP.md](https://github.com/apollographql/apollo-android/blob/main/ROADMAP.md) for more details) so I can't really comment on how that will take shape ultimately. If we end up removing the `fragment` altogether, I guess it'll have to be opt-in through some parameter or so because of the aforementioned name clashes, we can't really make that the default.

**Comment by heavyauto** [comment] 2021-03-11 15:43
That's great news! "opt-in through some parameter" sounds a good approach. I know you are focusing on the V3.0. but by any chance, do you think you could apply that change to the current stable version as well? 😄

**Comment by martinbonnin** [comment] 2021-03-11 15:51
I'll try to look into it but honestly can't promise anything as there's a lot on the todo list. 

Also, we do accept pull requests, feel free to take a shot at it if you feel like it?

**Comment by heavyauto** [comment] 2021-03-11 16:01
Ok, I understand. Sure, I'd like to try. Do you have any hint for me which packages I could start with? or do you have the branch you have done the changes for v3.0?

**Comment by martinbonnin** [comment] 2021-03-11 16:17
The `dev-3.x` branch is moving fast and doesn't have anything to skip `.fragments`. I was more referring to better handling of fragments as a general goal of `dev-3.x`, which might mean optionally skipping the `.fragments` meta-field but there are also other options on the table too like generating fragments as interfaces. If you want to take a quick look there, we publish `-dev` builds like https://repo1.maven.org/maven2/com/apollographql/apollo3/apollo-api/3.0.0-dev4/.

If your goal is to have optional skippable `.fragment` in main, I'd look in main first. 

To make all this work, you'll have to add a new parameter to the Gradle plugin ([here](https://github.com/apollographql/apollo-android/blob/main/apollo-gradle-plugin/src/main/kotlin/com/apollographql/apollo/gradle/api/CompilerParams.kt)) and forward that to the compiler to skip generating the .fragments accessors ([here](https://github.com/apollographql/apollo-android/blob/019edd04fdfe51f107061d0d74cb5025d58f2528/apollo-compiler/src/main/kotlin/com/apollographql/apollo/compiler/SchemaTypeSpecBuilder.kt#L156)). It's all doable but there's a fair amount of layers to go through.

**Comment by heavyauto** [comment] 2021-03-11 16:29
ok, thanks for the hints.

**Comment by martinbonnin** [comment] 2021-03-15 10:38
Hi 👋  ! Unfortunately, I haven't been able to reproduce the issue, either when the query is persisted or when it's not. So looks like there's more to the story. 

I made a tentative reproducer there: https://github.com/martinbonnin/apollo-android-samples/blob/main/apq-and-http-cache/README.md

Can you try to see if you spot a difference with your setup and/or try to make it fail?

**Comment by kicktipp** [comment] 2021-04-16 08:25
We use the generated Java-Code in some test classes and wonder why the generated code is using a .fragments() method while Apollo JS client is not? When we use the same query in our Vue frontend we can access the fragments directly by the name of the fragment. 

I think the generated code should reflect the json I get from the backend.

An option to skip the .fragments field is a good idea.

**Comment by martinbonnin** [comment] 2021-07-16 09:21
@kicktipp sorry for the delay. If you have an example of a query and corresponding Vue code, I'm super curious to see how it's like.

Kotlin is overall different and generating Json response based models that also keeps reusable can yield to [very complex code](https://github.com/apollographql/apollo-android/issues/3144).

@heavyauto Apollo Android 3 is now in alpha and you can try it out. It has different codegen options:
* `responseBased` generates models that map the Json response
* `operationBased` generates models that map the GraphQL query document
* `compat` is for compatibility with 2.x

See https://github.com/apollographql/apollo-android/blob/dev-3.x/design-docs/Codegen.md for more details. In particular, both `responseBased` and `operationBased` will skip `.fragments`

**Comment by martinbonnin** [comment] 2021-07-26 08:47
@kicktipp @heavyauto let us know if you want to dive in the different options there. If not, I'll mark this as fixed in `3.0.0-alpha01`

**Comment by martinbonnin** [comment] 2021-10-05 10:23
`3.0.0-alpha01` now skips `.fragments` in both `operationBased` and `responseBased` codegen. Closing.

**Closed by martinbonnin** 2021-10-05 10:23 UTC
Labels: Component: compiler, Type: Question, Status: waiting for info

**Comment by kicktipp** [comment] 2022-01-13 16:51
Sounds promising. I tried to use it but I still use java. And the documentation is only for kotlin. Two examples:

1.
https://www.apollographql.com/docs/kotlin/migration/3.0/#operation-apis
```apolloClient.query(query).execute()``` 
this does not work in java as it is a coroutine? I don't know how to get the response in java

2.
https://www.apollographql.com/docs/kotlin/tutorial/10-authenticate-your-queries/#use-the-interceptor
```   return ApolloClient.Builder()
        .serverUrl("https://apollo-fullstack-tutorial.herokuapp.com/graphql")
        .okHttpClient(okHttpClient)
        .build()
```
There is no method "okHttpclient" in 3.0.0. 

Quite difficult to use it if the docs are not made for java. I don't want to switch to kotlin yet.

**Comment by martinbonnin** [comment] 2022-01-13 17:12
@kicktipp indeed version 3 is mostly focused at Kotlin. 

You can make coroutine APIs work with Java by using something like [kotlinx-coroutines-rx2](https://github.com/Kotlin/kotlinx.coroutines/tree/master/reactive/kotlinx-coroutines-rx2). 

For `okHttpClient`, you can use the underlying `httpEngine` method:

```
apolloClientBuilder.httpEngine(DefaultHttpEngine(okHttpClient))
```

I agree it's not really idiomatic and I'm not sure we want to document that. If you want idiomatic Java support, please upvote and follow https://github.com/apollographql/apollo-kotlin/issues/3694. We might want to do a separate "Java-only" runtime in the future for idiomatic APIs
