### ISSUE TITLE
Multi modules: Execution failed for task ':checkServiceApolloDuplicates' in alpha-04.

### ISSUE THREAD

**Issue by ProVir** [apollographql/apollo-android#3340] opened 2021-09-08 09:42 UTC
Hi!

After upgrading to alpha-04, my project cannot compile, it shows an error:
```
Execution failed for task ':checkServiceApolloDuplicates'.
> duplicate Type 'ResolverKey(kind=CustomScalarTarget, id=Long)' generated in modules: api-graphql-kp,graphql-kp
  Use 'alwaysGenerateTypesMatching' in a parent module to generate the type only once

Cause: duplicate Type 'ResolverKey(kind=CustomScalarTarget, id=Long)' generated in modules: api-graphql-kp,graphql-kp
Use 'alwaysGenerateTypesMatching' in a parent module to generate the type only once
```

I tried adding to the parent and child modules - it does not help:
`alwaysGenerateTypesMatching.set(emptyList())`

**My environment:**
Parent module:
```
plugins {
    kotlin("multiplatform")
    id("com.android.library")
    id("com.apollographql.apollo3").version(Versions.apollo)
}

apollo {
    packageName.set("ru.kinopoisk.shared.api.graphqlkp.models")
    generateOperationOutput.set(true)
    generateApolloMetadata.set(true)
    alwaysGenerateTypesMatching.set(emptyList())

    customScalarsMapping.set(mapOf(
        "Long" to "kotlin.Long"
    ))
}
```

Child module:
```
plugins {
    kotlin("multiplatform")
    id("com.android.library")
    id("com.apollographql.apollo3").version(Versions.apollo)
}

apollo {
    packageName.set("ru.kinopoisk.shared.movielist.api.graphqlkp.models")
    generateOperationOutput.set(true)
    generateApolloMetadata.set(true)
    alwaysGenerateTypesMatching.set(emptyList())
}

dependencies {
    apolloMetadata(project(Modules.API.graphqlkp))
}
```

**Comment by martinbonnin** [comment] 2021-09-08 10:18
Looks like you have only 2 modules? 

* `graphql-kp`: parent module?
* `api-graphql-kp`: child module?

If that's the case, it's most likely a bug. `api-graphql-kp` should see that the custom scalar is generated in `graphql-kp` and not generate it. I'll look into it. 

In all cases, can you try setting this in your root module? 

```
apollo {
    alwaysGenerateTypesMatching.set(listOf("CustomScalarTarget"))
}
```

**Comment by martinbonnin** [comment] 2021-09-08 10:43
Found the bug. It's there: https://github.com/apollographql/apollo-android/blob/09e654447c87dd8c4177b796c590878ce8ee380d/apollo-compiler/src/main/kotlin/com/apollographql/apollo3/compiler/codegen/kotlin/KotlinCodeGen.kt#L80.

This generates a false positive entry even if no code is actually generated :/. I'll try to think of a workaround. If not, I'll make a quick fix.

**Comment by martinbonnin** [comment] 2021-09-08 12:04
Fix is there: https://github.com/apollographql/apollo-android/pull/3341. Thanks for catching this. It'll be in next version. 

In the meantime, you should be able to workaround this issue by adding this to your root project `build.gradle.kts`:

```kotlin
tasks.all {
  if (name == "checkServiceApolloDuplicates") {
    enabled = false
  }
}
```

**Comment by ProVir** [comment] 2021-09-09 08:53
> Fix is there: #3341. Thanks for catching this. It'll be in next version.
> 
> In the meantime, you should be able to workaround this issue by adding this to your root project `build.gradle.kts`:
> 
> ```kotlin
> tasks.all {
>   if (name == "checkServiceApolloDuplicates") {
>     enabled = false
>   }
> }
> ```
> 
> That will disable the check. If you have no real duplicates (and not false positives like this one), this should do the trick.

Thank you, it helped! I will wait for alpha 05 with a fix to remove this temporary solution.

**Comment by martinbonnin** [comment] 2021-09-16 14:31
Fixed in `alpha05`

**Comment by ProVir** [comment] 2021-09-16 16:35
@martinbonnin Hi!
I upgraded to alpha06 and now I have another problem.

![image](https://user-images.githubusercontent.com/7127304/133650584-6130152d-cbe0-428d-bda1-bcc201085c34.png)

The Long type began to come as Any type.

I have my own CustomScalarAdapter and it worked in alpha04.

**Comment by martinbonnin** [comment] 2021-09-16 17:26
Yikes, sorry about that. I can reproduce here: https://github.com/apollographql/apollo-android/commit/04f86d21eb2e3cbe575bf856585f476b27bf8227. Will dig into this.

**Comment by martinbonnin** [comment] 2021-09-16 21:40
`3.0.0-alpha07-SNAPSHOT` should have the fix now.

**Comment by ProVir** [comment] 2021-09-17 12:40
> `3.0.0-alpha07-SNAPSHOT` should have the fix now.

I checked it, now it works perfectly.

**Comment by martinbonnin** [comment] 2021-09-17 14:25
Thanks for the heads up 🙏 . I'm still looking into that other `IndexOutOfBands` error and I'll make a new alpha, certainly next week.

**Closed by martinbonnin** 2021-09-17 14:25 UTC
Labels: Type: Bug, 2021-09

**Comment by SumeraMartin** [comment] 2021-11-05 17:21
I have the following setup with beta-02:

Network modules:
```
plugins {
    id("com.android.library")
    id("com.apollographql.apollo3").version(Versions.apollo)
}

apollo {
    packageName.set("package.network")
    generateApolloMetadata.set(true) // Allow GraphQL query generation for multi-module project
    alwaysGenerateTypesMatching.set(listOf(".*"))
}
```

App module:
```
plugins {
    id("com.android.application")
    id("com.apollographql.apollo3").version(Versions.apollo)
}

apollo {
     packageName.set("package.app")
}

dynamicFeatures.apply {
    add(":dynamicModule")
}


with query:

query GetAvailableDevices {
    entities {
        id
    }
}
```

Dynamic module
```
plugins {
    id("com.android.dynamic-feature")
    id("com.apollographql.apollo3").version(Versions.apollo)
}

apollo {
    packageName.set("package.dynamicModule")
}


with query:

query GetAvailableDevices {
    entities {
        id
    }
}
```
The modules have the following relation:

[network]<--[app]<--[dynamic]

I'm getting the following error with this setup:

```
Execution failed for task ':checkServiceApolloDuplicates'.
> duplicate Type 'ResolverKey(kind=SchemaType, id=GetAvailableDevices)' generated in modules: app,dynamicModule
  Use 'alwaysGenerateTypesMatching' in a parent module to generate the type only once
```

I have tried to set alwaysGenerateTypesMatching in the network module and also in the app module and in the dynamic module. Looks like none of them works.

I have tried it with the following setup
`alwaysGenerateTypesMatching.set(emptyList())`
`alwaysGenerateTypesMatching.set(listOf(".*"))`

The only thing that works is to set
`alwaysGenerateTypesMatching.set(listOf("GetAvailableDevices"))`
in the network module, but I would like to avoid it since there will be a lot of these types.

Looks like a bug to me or I misunderstood the documentation somehow. @martinbonnin
