### ISSUE TITLE
New nullability annotations on custom type adapters break nullable types

### ISSUE THREAD

**Issue by hzsweers** [apollographql/apollo-android#700] opened 2017-10-21 12:10 UTC
In 0.4.2 - nullable fields backed by custom types will break because the CustomTypeAdapter API only allows for returning nonnull values. in loosely checked Java code this flies, but in kotlin it becomes either a compile error or runtime error (if it is null and you used `!!`).

Will link a repro branch tomorrow but putting up for visibility now. I think either the return nullability should be relaxed or a nullsafe wrapper should be introduced and used in the event of nullable types. The former is probably more flexible, as the only way the latter works is if the nullsafe adapter try/catches the delegate adapter

**Comment by sav007** [comment] 2017-10-21 18:41
@digitalbuddha  @hzsweers I'm sorry, a little confused, what the issue? For nullable fields backed by custom types if it's value null we don't call registered `CustomTypeAdapter` but set to `null` right away.

**Comment by hzsweers** [comment] 2017-10-21 22:48
Here's a repro branch: https://github.com/hzsweers/CatchUp/tree/z/apollo042

The generated code issue is in `GithubSearchQuery$AsRepository$Mapper#map`, this line in particular

```java
final HttpUrl homepageUrl = reader.readCustomType((ResponseField.CustomTypeField) $responseFields[4]);
```

This doesn't handle the nullability of the `homepageUrl` field, and delegates directly to the `HttpUrlAdapter` implementation, which must nullcheck now in order to compile

```kotlin
class HttpUrlApolloAdapter : CustomTypeAdapter<HttpUrl> {
  override fun decode(s: String) = HttpUrl.parse(s)!!

  override fun encode(o: HttpUrl) = o.toString()
}
```

This results in the following trace at runtime during deserialization if that field is null

```
10-21 04:00:46.340 2603-2603/io.sweers.catchup.debug E/ServiceController$loadD: HttpException
                                                                                com.apollographql.apollo.exception.ApolloParseException: Failed to parse http response
                                                                                    at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:101)
                                                                                    at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.access$100(ApolloParseInterceptor.java:28)
                                                                                    at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:53)
                                                                                    at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$1$1.onResponse(ApolloServerInterceptor.java:93)
                                                                                    at com.google.firebase.perf.network.zzg.onResponse(Unknown Source:16)
                                                                                    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
                                                                                    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                    at java.lang.Thread.run(Thread.java:764)
                                                                                 Caused by: kotlin.KotlinNullPointerException
                                                                                    at io.sweers.catchup.data.HttpUrlApolloAdapter.decode(HttpUrlApolloAdapter.kt:26)
                                                                                    at io.sweers.catchup.data.HttpUrlApolloAdapter.decode(HttpUrlApolloAdapter.kt:25)
                                                                                    at com.apollographql.apollo.internal.response.RealResponseReader.readCustomType(RealResponseReader.java:189)
                                                                                    at io.sweers.catchup.service.github.GitHubSearchQuery$AsRepository$Mapper.map(GitHubSearchQuery.java:920)
                                                                                    at io.sweers.catchup.service.github.GitHubSearchQuery$Node$Mapper$1.read(GitHubSearchQuery.java:667)
                                                                                    at io.sweers.catchup.service.github.GitHubSearchQuery$Node$Mapper$1.read(GitHubSearchQuery.java:664)
                                                                                    at com.apollographql.apollo.internal.response.RealResponseReader.readConditional(RealResponseReader.java:215)
                                                                                    at io.sweers.catchup.service.github.GitHubSearchQuery$Node$Mapper.map(GitHubSearchQuery.java:664)
                                                                                    at io.sweers.catchup.service.github.GitHubSearchQuery$Search$Mapper$2$1.read(GitHubSearchQuery.java:461)
                                                                                    at io.sweers.catchup.service.github.GitHubSearchQuery$Search$Mapper$2$1.read(GitHubSearchQuery.java:458)
                                                                                    at com.apollographql.apollo.internal.response.RealResponseReader$ListItemReader.readObject(RealResponseReader.java:306)
                                                                                    at io.sweers.catchup.service.github.GitHubSearchQuery$Search$Mapper$2.read(GitHubSearchQuery.java:458)
                                                                                    at io.sweers.catchup.service.github.GitHubSearchQuery$Search$Mapper$2.read(GitHubSearchQuery.java:455)
                                                                                    at com.apollographql.apollo.internal.response.RealResponseReader.readList(RealResponseReader.java:163)
                                                                                    at io.sweers.catchup.service.github.GitHubSearchQuery$Search$Mapper.map(GitHubSearchQuery.java:455)
                                                                                    at io.sweers.catchup.service.github.GitHubSearchQuery$Data$Mapper$1.read(GitHubSearchQuery.java:314)
                                                                                    at io.sweers.catchup.service.github.GitHubSearchQuery$Data$Mapper$1.read(GitHubSearchQuery.java:311)
                                                                                    at com.apollographql.apollo.internal.response.RealResponseReader.readObject(RealResponseReader.java:136)
                                                                                    at io.sweers.catchup.service.github.GitHubSearchQuery$Data$Mapper.map(GitHubSearchQuery.java:311)
                                                                                    at io.sweers.catchup.service.github.GitHubSearchQuery$Data$Mapper.map(GitHubSearchQuery.java:306)
                                                                                    at com.apollographql.apollo.internal.response.OperationResponseParser$1.read(OperationResponseParser.java:56)
                                                                                    at com.apollographql.apollo.internal.json.ResponseJsonStreamReader.nextObject(ResponseJsonStreamReader.java:86)
                                                                                    at com.apollographql.apollo.internal.response.OperationResponseParser.parse(OperationResponseParser.java:51)
                                                                                    at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:87)
                                                                                    at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.access$100(ApolloParseInterceptor.java:28) 
                                                                                    at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:53) 
                                                                                    at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$1$1.onResponse(ApolloServerInterceptor.java:93) 
                                                                                    at com.google.firebase.perf.network.zzg.onResponse(Unknown Source:16) 
                                                                                    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153) 
                                                                                    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                                                    at java.lang.Thread.run(Thread.java:764) 
```

**Comment by sav007** [comment] 2017-10-22 02:44
That's weird because if you take a look at https://github.com/apollographql/apollo-android/blob/master/apollo-runtime/src/main/java/com/apollographql/apollo/internal/response/RealResponseReader.java#L183

We handle the `null` value

**Comment by sav007** [comment] 2017-10-22 02:46
Agh wait, are you returning `null` as the result of `fun decode(s: String)` in your adapter?

**Comment by hzsweers** [comment] 2017-10-22 03:14
No, the point is I can't because the annotations don't allow it :)

**Comment by sav007** [comment] 2017-10-22 14:23
Hm I see, so yeah if we pass to custom adapter a raw value (string) that is not null then we expect adapter to return decoded non null value back . 
I guess in your case the problem is `HttpUrl.parse`  returns null, I wish OkHttp3 provided smth similar to `Uri.EMPTY` instead of null. 

Doesn't it looks strange backend returns some non-null value in the response but custom type adapter converts it to null?

What we can do is to remove `NonNull` annotation from adapter interface to allow return null values and validate nullability for non-null fields on our end. 

```
@Nullable
public static HttpUrl parse(String url)
Returns a new HttpUrl representing url if it is a well-formed HTTP or HTTPS URL, or null if it isn't.
```

**Comment by digitalbuddha** [comment] 2017-10-22 17:16
@swankjesse any chance you've thought about changes to how the http parse api works? We can work around it but I wanted to reach out to see if you had pending changes to be more kotlin friendly.

**Comment by digitalbuddha** [comment] 2017-10-22 19:15
@hzsweers  took this offline with Jesse this was the tldr `It's not a null/non-null null problem, it's a valid/invalid URL problem, And you can decide what to do with invalid URLs however you like
Crashing, returning a default value, returning null`  

The issue isn't that we don't handle null correctly, the issue is that you are not validating whether something is an actual URL prior to sending it to the `HttpURL.parse`. I don't believe we need to make any changes on our end as this is an implementation detail of your adapter and what it delegates to

**Comment by sav007** [comment] 2017-10-25 01:26
@hzsweers @digitalbuddha so should we close this issue? Or we need to do some changes on our end?

**Comment by digitalbuddha** [comment] 2017-10-25 01:29
I like your suggestion
What we can do is to remove NonNull annotation from adapter interface to allow return null values and validate nullability for non-null fields on our end. 

I vote for that if not much effort

**Comment by hzsweers** [comment] 2017-10-25 14:37
Yep I agree with the plan above :)

**Closed** 2017-10-27 02:06 UTC
