### ISSUE TITLE
Unable to delete file apollo-codegen\package.json

### ISSUE THREAD

**Issue by AyupovIlgam** [apollographql/apollo-android#1332] opened 2019-05-29 13:08 UTC
It seems that there is some gradle integration issue!

It appears on gradle version **com.android.tools.build:gradle:3.4.1**
distributionUrl=https\://services.gradle.org/distributions/**gradle-5.1.1-all.zip**

Logs:

> Unable to delete file {path to project's build folder}\apollo-codegen\package.json

Issue dissapears when I revert my changes to:
classpath '**com.android.tools.build:gradle:3.2.1**'
distributionUrl=https\://services.gradle.org/distributions/**gradle-4.10.1-all.zip**

**Comment by sav007** [comment] 2019-06-01 04:47
it might be fixed via https://github.com/apollographql/apollo-android/pull/1338

**Comment by andrepiper** [comment] 2019-06-07 23:25
@sav007 thanks for the update. I'm experiencing this now.

**Comment by altairmizuchi** [comment] 2019-06-19 09:18
![image](https://user-images.githubusercontent.com/7736121/59753182-2ee56700-92b6-11e9-985c-375779d9123c.png)
Hello! The issue is still presented. Rebuilding project does not help. But killing stuck java.exe process does!
Here is my java version
![image](https://user-images.githubusercontent.com/7736121/59753230-41f83700-92b6-11e9-9605-912c69732f14.png)

**Comment by sav007** [comment] 2019-08-22 23:34
Please try latest version with a new code generation engine https://github.com/apollographql/apollo-android/releases/tag/1.1.0

If you see the same issue pls reopen.

**Closed by sav007** 2019-08-22 23:34 UTC
