### ISSUE TITLE
Fragment generated as nullable in Kotlin

### ISSUE THREAD

**Issue by lwasyl** [apollographql/apollo-android#1769] opened 2019-11-14 19:57 UTC
Given a nested fragment:
```graphql
query User {
    viewer {
        viewerRole {
            ...nestedData
        }
    }
}
fragment nestedData on ViewerRole {
     // stuff
    ...availabilityData
}

fragment availabilityData on ViewerRole {
  available
  // stuff
}
```
it is generated as nullable for me:
```kotlin
class UserData(
 // stuff
 val fragments: Fragments
) { 
    data class Fragments(
      val availabilityData: AvailabilityData?
    ) {
}
```

This doesn't seem correct, since `available` and more fields under `availabilityData` are non-nullable. Should it be generated as nullable in this case or it's a bug?

Sorry for not a very clear repro, I have pretty big schema and query files and it's kind of difficult to isolate just the relevant parts. Maybe related, `fragment availabilityData` is in a different query file than the rest.
**Version**
1.2.1

**Comment by sav007** [comment] 2019-11-17 03:16
It's probably not a bug as nullability of `fragments.availabilityData` depends on the type condition of `UserData` rather than on the fact all fields aren't nullable. For instance, having this query and fragments:

```
query TestQuery {
  hero {
    __typename
    ...HeroDetails
    ...HumanDetails
  }
}

fragment HeroDetails on Character {
  __typename
  name
  ... HumanDetails
}

fragment HumanDetails on Human {
  __typename
  name
}
```

Will generate this:
```
data class Fragments(
      val heroDetails: HeroDetails,
      val humanDetails: HumanDetails?
)
```

Why:
- `HeroDetails` is defined on `Character` and because `hero` field in the schema has type `Character` Apollo knows exactly that it won't be optional
- `HumanDetails` on the other hand defined on `Human`, that is the subclass of `Character` and it can be a case when the response can return another subclass `Droid` , that's why it's optional.

So it's not a bug.

**Comment by sav007** [comment] 2019-11-21 19:29
Cleanup, closing.

**Closed by sav007** 2019-11-21 19:29 UTC
Labels: Type: Question

**Comment by lwasyl** [comment] 2019-11-21 20:52
Hey, sorry for late response, I didn't quite have time to get back into this issue. There are no multiple types involved, though, the schema is pretty straightforward:

```graphql
type Viewer {
 viewerRole: ViewerRole!
}

type ViewerRole {
 available: String!
}
```

When I move the query so that it is not nested:
```graphql
query User {
    viewer {
        viewerRole {
            ...availabilityData
            ...nestedData
        }
    }
}
fragment nestedData on ViewerRole {
     // stuff

}

fragment availabilityData on ViewerRole {
  available
  // stuff
}
```

Then `UserQuery.Data#viewer#viewerRole#fragments#availabilityData` is _not_ nullable. It only starts being nullable when I use fragment within fragment on the same type, which still doesn't seem right to me.

When I inline `...availabilityData` fragment in any place, I get non-nullable values for all the fields defined inside the fragment, as expected. When I don't nest fragments, they are non-nullable as well. I'd expect in this case that wrapping stuff in a fragment will always result in a non-nullable fragment with perhaps nullable fields, if anything inside could be not present.

**Comment by lwasyl** [comment] 2019-12-03 22:37
@sav007 Pinging in case you missed message in an already closed issue. Based on the above example it still seems to me the fragment shouldn't be generated as nullable, could you take another look?
