### ISSUE TITLE
SQLiteDatabaseLockedException: database is locked (code 5)

### ISSUE THREAD

**Issue by fame1237** [apollographql/apollo-android#1065] opened 2018-09-28 06:54 UTC
`Caused by android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): , while compiling: PRAGMA journal_mode
#################################################################
Error Code : 5 (SQLITE_BUSY)
Caused By : The database file is locked.
	(database is locked (code 5): , while compiling: PRAGMA journal_mode)
#################################################################
       at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1006)
       at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:710)
       at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:387)
       at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:361)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:250)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:201)
       at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:514)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:178)
       at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:934)
       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:895)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:708)
       at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:646)
       at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:283)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
       at com.apollographql.apollo.cache.normalized.sql.SqlNormalizedCache.(SqlNormalizedCache.java:64)
       at com.apollographql.apollo.cache.normalized.sql.SqlNormalizedCacheFactory.create(SqlNormalizedCacheFactory.java:16)
       at com.apollographql.apollo.cache.normalized.sql.SqlNormalizedCacheFactory.create(SqlNormalizedCacheFactory.java:8)
       at com.apollographql.apollo.cache.normalized.NormalizedCacheFactory.createChain(NormalizedCacheFactory.java:36)
       at com.apollographql.apollo.cache.normalized.NormalizedCacheFactory$1.apply(NormalizedCacheFactory.java:32)
       at com.apollographql.apollo.cache.normalized.NormalizedCacheFactory$1.apply(NormalizedCacheFactory.java:30)
       at com.apollographql.apollo.api.internal.Present.map(Present.java:63)
       at com.apollographql.apollo.cache.normalized.NormalizedCacheFactory.createChain(NormalizedCacheFactory.java:30)
       at com.apollographql.apollo.ApolloClient$Builder.build(ApolloClient.java:510)
       at co.fictionlog.fictionlog.manager.graphql.MyApolloQueryClient.(MyApolloQueryClient.kt:124)
       at co.fictionlog.fictionlog.fragment.bookdetail.ChapterFragment$getBookDetail$3.accept(ChapterFragment.kt:292)
       at co.fictionlog.fictionlog.fragment.bookdetail.ChapterFragment$getBookDetail$3.accept(ChapterFragment.kt:39)
       at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:59)
       at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
       at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7406)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

**Comment by sav007** [comment] 2019-08-24 19:50
Closing for now, couldn't reproduce.

**Closed by sav007** 2019-08-24 19:50 UTC
Labels: investigation
