### ISSUE TITLE
Compiler fails when using multi-module (2.4.1)

### ISSUE THREAD

**Issue by BreSmit521** [apollographql/apollo-android#2678] opened 2020-10-20 14:40 UTC
Currently attempting to convert an existing project to multi-module support and am running into this crash when attempting to compile my project.
![image](https://user-images.githubusercontent.com/12717711/96600803-3354d200-12a6-11eb-96d1-b6c8818d1ad4.png)

My project consists of 4 modules, the relevant 2 being "app" and "commons" 

The build.gradle for "app" looks like this:

```groovy
apply plugin: 'com.android.application'
apply plugin: 'com.apollographql.apollo'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'maven-publish'
apply plugin: 'kotlin-kapt'
apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'com.google.firebase.firebase-perf'
apply plugin: 'de.mannodermaus.android-junit5'

...

dependencies {
  implementation "com.apollographql.apollo:apollo-runtime:2.4.1"
  apolloMetadata project(':common')
  api project(':common')
  ...
}
```

The build.gradle for "commons" looks like this:

```groovy
apply plugin: 'com.android.library'
apply plugin: 'com.apollographql.apollo'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'com.jfrog.artifactory'
apply plugin: 'maven-publish'
apply plugin: 'kotlin-kapt'

...

apollo {
  generateKotlinModels = true
  generateApolloMetadata = true
  customTypeMapping = [
      "DateTime": "org.joda.time.DateTime",
      "GeoJSON": "org.geojson.GeoJsonObject",
      "QUERYSTRING": "kotlin.String",
      "JSON": "com.fasterxml.jackson.databind.JsonNode",
      "Upload": "com.apollographql.apollo.api.FileUpload",
      "Regex": "kotlin.String"
  ]
}
```

Pre multi-module we pointed to the path of the schema (which lives in commons) via a relative path in the "app" build.gradle via a service: 

```
apollo {
  service("core") {
    schemaPath = "../../../../common/src/main/graphql/schema.json"
    rootPackageName = "com.coolfire.core.android.app.graphql.query"
  }
}
```

But I wasn't sure if this was even still necessary in multi-module support and actually causes another issue when leaving it in.  So I have removed it entirely

Thanks in advance and if you need anything else let me know!

**Comment by martinbonnin** [comment] 2020-10-20 14:52
Interesting, this crash happens in `kapt`. Can you check a clean build to eliminate any stale cache/build cache issue? 

```
rm -rf build */build
./gradlew clean :app:assembleDebug --no-build-cache
```

**Comment by BreSmit521** [comment] 2020-10-20 15:16
Thanks for the quick reply, unfortunately same issue after taking those steps.

**Comment by martinbonnin** [comment] 2020-10-20 15:33
Thanks for verifying this. This seems to happen in the `commons` module, which should simplify the debugging a bit as we can certainly exclude `app` from investigations for the time being. A few things to try:

* `./gradlew :commons:generateApolloSources` -> this should work well 
* `./gradlew :commons:kaptGenerateStubsDebugKotlin` -> this should fail
* bisect on the graphql files to see if the error comes from a specific one. Start by removing all the files from common and run `./gradlew :commons:kaptGenerateStubsDebugKotlin` then add them progressively until it fails again.

If you could upload a small reproducer somewhere or email it (my email is in git), that'd help a lot as I've never seen such an issue with kapt.

**Comment by BreSmit521** [comment] 2020-10-20 16:57
Excellent, that's actually incredibly easy since there's only one graphql file in the commons package currently (this was used to allow us to generate CustomType adapters since it doesn't seem like the custom types in the enum are generated if they're not used in any queries in the module). 

Deleting that file did allow us  to get further though to what I think may be the root of the issue: 
![image](https://user-images.githubusercontent.com/12717711/96616688-8edb8b80-12b7-11eb-8722-29ef18c487d4.png)

Interestingly enough that only appears if I remove the one single graphql file in commons completely.  If I remove/comment out all the contents the initial issue still occurs.

I will see if I can reproduce this via a sample app and get back to you.  Thanks again for all the help!

**Comment by martinbonnin** [comment] 2020-10-20 17:04
> the custom types in the enum are generated if they're not used in any queries in the module

This actually changes with multi-modules. Because the parent modules doesn't know in advance what custom types might be used by child modules, the parent module should now generate all types. That might be a hint.

You can experiment with [alwaysGenerateTypesMatching](https://www.apollographql.com/docs/android/advanced/multi-modules/#big-schemas) to investigate what type makes the Kotlin compiler choke:

```
// common/build.gradle.kts
apollo {
    generateApolloMetadata.set(true)
    // Generate all types (default)
    alwaysGenerateTypesMatching.set(listOf(".*"))
    // This will only generate these types (and the ones that are used by the queries)
    alwaysGenerateTypesMatching.set(listOf("CommonInputType", "CommonEnum"))
}
```

**Comment by martinbonnin** [comment] 2020-10-23 18:53
I could reproduce a problem where the Kotlin compiler would take a huge amount of time (gave up after 15min) due to generating all the input types. This was fixed when I put `alwaysGenerateTypesMatching.set(emptyList())` so I'm going to assume this was the problem and close the issue. Please leave a message if you want me to reopen it.

**Closed by martinbonnin** 2020-10-23 18:53 UTC
