### ISSUE TITLE
Remove or Feature to silence code gen output

### ISSUE THREAD

**Issue by jaredsburrows** [apollographql/apollo-android#549] opened 2017-07-06 23:57 UTC
How can we remove/silence this tasks's output? Can you all no print this out when your plugin runs or add an option to the gradle extension to suppress this verbose out?

Here is an example via command line:
```
> Task :installApolloCodegen
apollo-android@0.0.1 /<>/build/apollo-codegen
`-- apollo-codegen@0.12.10 
  +-- change-case@3.0.1 
  | +-- camel-case@3.0.0 
  | +-- constant-case@2.0.0 
  | +-- dot-case@2.1.1 
  | +-- header-case@1.0.1 
  | +-- is-lower-case@1.1.3 
  | +-- is-upper-case@1.1.2 
  | +-- lower-case@1.1.4 
  | +-- lower-case-first@1.0.2 
  | +-- no-case@2.3.1 
  | +-- param-case@2.1.1 
  | +-- pascal-case@2.0.1 
  | +-- path-case@2.1.1 
  | +-- sentence-case@2.1.1 
  | +-- snake-case@2.1.0 
  | +-- swap-case@1.1.2 
  | +-- title-case@2.1.1 
  | +-- upper-case@1.1.3 
  | `-- upper-case-first@1.1.2 
  +-- core-js@2.4.1 
  +-- glob@7.1.2 
  | +-- fs.realpath@1.0.0 
  | +-- inflight@1.0.6 
  | | `-- wrappy@1.0.2 
  | +-- inherits@2.0.3 
  | +-- minimatch@3.0.4 
  | | `-- brace-expansion@1.1.8 
  | |   +-- balanced-match@1.0.0 
  | |   `-- concat-map@0.0.1 
  | +-- once@1.4.0 
  | `-- path-is-absolute@1.0.1 
  +-- graphql@0.10.3 
  | `-- iterall@1.1.1 
  +-- inflected@1.1.7 
  +-- mkdirp@0.5.1 
  | `-- minimist@0.0.8 
  +-- node-fetch@1.7.1 
  | +-- encoding@0.1.12 
  | | `-- iconv-lite@0.4.18 
  | `-- is-stream@1.1.0 
  +-- source-map-support@0.4.15 
  | `-- source-map@0.5.6 
  `-- yargs@8.0.2 
    +-- camelcase@4.1.0 
    +-- cliui@3.2.0 
    | +-- string-width@1.0.2 
    | | +-- code-point-at@1.1.0 
    | | `-- is-fullwidth-code-point@1.0.0 
    | |   `-- number-is-nan@1.0.1 
    | +-- strip-ansi@3.0.1 
    | | `-- ansi-regex@2.1.1 
    | `-- wrap-ansi@2.1.0 
    |   `-- string-width@1.0.2 
    +-- decamelize@1.2.0 
    +-- get-caller-file@1.0.2 
    +-- os-locale@2.0.0 
    | +-- execa@0.5.1 
    | | +-- cross-spawn@4.0.2 
    | | | +-- lru-cache@4.1.1 
    | | | | +-- pseudomap@1.0.2 
    | | | | `-- yallist@2.1.2 
    | | | `-- which@1.2.14 
    | | |   `-- isexe@2.0.0 
    | | +-- get-stream@2.3.1 
    | | | +-- object-assign@4.1.1 
    | | | `-- pinkie-promise@2.0.1 
    | | |   `-- pinkie@2.0.4 
    | | +-- npm-run-path@2.0.2 
    | | | `-- path-key@2.0.1 
    | | +-- p-finally@1.0.0 
    | | +-- signal-exit@3.0.2 
    | | `-- strip-eof@1.0.0 
    | +-- lcid@1.0.0 
    | | `-- invert-kv@1.0.0 
    | `-- mem@1.1.0 
    |   `-- mimic-fn@1.1.0 
    +-- read-pkg-up@2.0.0 
    | +-- find-up@2.1.0 
    | | `-- locate-path@2.0.0 
    | |   +-- p-locate@2.0.0 
    | |   | `-- p-limit@1.1.0 
    | |   `-- path-exists@3.0.0 
    | `-- read-pkg@2.0.0 
    |   +-- load-json-file@2.0.0 
    |   | +-- graceful-fs@4.1.11 
    |   | +-- parse-json@2.2.0 
    |   | | `-- error-ex@1.3.1 
    |   | |   `-- is-arrayish@0.2.1 
    |   | +-- pify@2.3.0 
    |   | `-- strip-bom@3.0.0 
    |   +-- normalize-package-data@2.4.0 
    |   | +-- hosted-git-info@2.5.0 
    |   | +-- is-builtin-module@1.0.0 
    |   | | `-- builtin-modules@1.1.1 
    |   | +-- semver@5.3.0 
    |   | `-- validate-npm-package-license@3.0.1 
    |   |   +-- spdx-correct@1.0.2 
    |   |   | `-- spdx-license-ids@1.2.2 
    |   |   `-- spdx-expression-parse@1.0.4 
    |   `-- path-type@2.0.0 
    +-- require-directory@2.1.1 
    +-- require-main-filename@1.0.1 
    +-- set-blocking@2.0.0 
    +-- string-width@2.1.0 
    | +-- is-fullwidth-code-point@2.0.0 
    | `-- strip-ansi@4.0.0 
    |   `-- ansi-regex@3.0.0 
    +-- which-module@2.0.0 
    +-- y18n@3.2.1 
    `-- yargs-parser@7.0.0 
```

And via Intellij:
<img width="848" alt="screen shot 2017-07-06 at 7 18 44 pm" src="https://user-images.githubusercontent.com/1739848/27940548-0d9fcc06-6280-11e7-82c9-0f0572e1923f.png">

**Comment by sav007** [comment] 2017-07-07 18:17
@marwanad I know you mentioned smth about this behaviour, but can we do anything here?

**Comment by jaredsburrows** [comment] 2017-07-07 18:19
@sav007 It would be nice to remove that print out entirely as it shows up as errors in Intellij.

**Comment by digitalbuddha** [comment] 2017-07-07 18:23
It's not us it's the upstream nodejs gradle plugin. They seem to put successful logs into error Logger

**Comment by marwanad** [comment] 2017-07-07 18:23
I thought I fixed that with #323. I'll double check tonight.

**Comment by marwanad** [comment] 2017-07-07 18:24
@jaredsburrows what version of apollo-android are you running?

**Comment by jaredsburrows** [comment] 2017-07-07 18:25
Sorry about that. I forgot to include that in the original post, version `0.3.2`.

**Comment by jaredsburrows** [comment] 2017-07-07 18:28
Seems to be the latest: https://mvnrepository.com/artifact/com.apollographql.apollo/gradle-plugin.

**Comment by marwanad** [comment] 2017-07-08 16:53
@jaredsburrows just ran it on a clean project and those messages were hidden. 

Are you overriding the task logging options by any chance? Running `gradle installApolloCodegen --info` would show these messages.

**Comment by jaredsburrows** [comment] 2017-07-09 20:38
@marwanad I do not override the logging and I am not using `--info`.

I am using this plugin in an android library module with Gradle 4.0.

**Comment by jaredsburrows** [comment] 2017-07-12 20:28
Any update on this? This is showing up as "errors" in Android Studio and Intellij confusing developers.

**Comment by marwanad** [comment] 2017-07-12 20:47
I'll take another look at this tonight.

I didn't see any of those errors on a clean project build (and none of those dependencies showed in the output of `gradle installApolloCodegen`). We're also capturing stdout and forwarding to Gradle logging under `INFO` level.

@sav007 are you also still seeing this in your project?

**Comment by jaredsburrows** [comment] 2017-07-12 21:29
@marwanad I am not calling that task directly. It is automatically called when compiling the android app in another module. The app is also being built with Gradle's parallel option. Wasn't that fix that was mentioned here added just recently?

**Comment by marwanad** [comment] 2017-07-13 15:57
@jaredsburrows The fix has been there for a while. 
Would you be able to provide a sample project so I can try it on that? 

Since it is automatically called, I think whatever is calling `gradle build` on that app module runs a `gradle build --info`.

**Comment by jaredsburrows** [comment] 2017-07-13 17:15
I am not using `gradlew build`. I am using this with an Android project. And nothing is calling `--info`, I am simply running `gradlew assembleDebug`.

**Comment by jaredsburrows** [comment] 2017-07-13 17:17
Cleaning the project via `gradlew clean` and then running `gradlew installApolloCodegen` directly outputs nothing but running `gradlew assembleDebug` from the root does show the output of `gradlew installApolloCodegen`.

**Comment by jaredsburrows** [comment] 2017-07-13 17:27
@sav007 @marwanad Turning off `--parallel`, I no longer see the output of the `gradlew installApolloCodegen`. So either this is a problem with this plugin trying to silence `npm` or something wrong with Gradle `4.0.1`?

**Comment by jaredsburrows** [comment] 2017-07-13 17:40
See https://discuss.gradle.org/t/logging-capturestandardoutput-does-not-capture-all-stdout-when-running-in-parallel/1147
which leads to https://issues.gradle.org/browse/GRADLE-3000.

I am thinking we might have to file another issue for Gradle in it's Github.

**Comment by jaredsburrows** [comment] 2017-07-13 17:44
It looks like you might have to use this newer API: https://github.com/gradle/gradle/blob/master/design-docs/features/composite-build/tooling-api/capture-output.md#overview.

**Comment by jaredsburrows** [comment] 2017-07-13 17:50
I made a Github issue for Gradle here: https://github.com/gradle/gradle/issues/2466.

**Comment by marwanad** [comment] 2017-07-13 17:56
Yeah, there were some changes introduced with Gradle 4.0 Logging, so I might have to revisit that. I'll take a look later tonight.

**Comment by jaredsburrows** [comment] 2017-07-13 18:04
@marwanad Yeah I know its coming from `gradle-node`. Is there a reason why we need to use that plugin for this plugin?

**Comment by digitalbuddha** [comment] 2017-07-13 18:09
Apollo has js code gen that builds an intermediate representation. That IR is used within apollo iOS and android. So before we run our kotlin code gen we take the  IR as an input.

**Comment by jaredsburrows** [comment] 2017-07-13 18:10
@digitalbuddha Alright thanks.

@marwanad I am glad we got this issue narrowed down to `gradlew --parallel`. Hopefully they can provide some insight on the issue I filed with them. Hopefully it is just a bug or API usage issue.

**Comment by jaredsburrows** [comment] 2017-07-14 19:42
Just confirmed that this is still an issue in `0.3.3`, the latest version.

**Comment by jaredsburrows** [comment] 2017-07-25 17:47
After upgrading to Gradle `4.1-rc-1`, here is what I see:

```
> Task :yammer-data:installApolloCodegen
apollo-android@0.0.1 /Users/jaburrow/repo/android2/yammer-data/build/apollo-codegen
`-- apollo-codegen@0.12.10 
```

**Comment by marwanad** [comment] 2017-07-26 14:28
@jaredsburrows Is that on a parallel build as well? It seems like it's caused by `GRADLE-3000`, as you suggested, which should go away with the improved console changes.

**Comment by jaredsburrows** [comment] 2017-07-26 16:46
@marwanad Yes and let's hope!

**Comment by jaredsburrows** [comment] 2017-10-28 03:07
Just to bump this, I am still seeing this with Gradle `4.2.1`.

**Comment by hzsweers** [comment] 2017-11-26 01:00
Ping on this, with the newer kotlin integration in intelliJ for build details, it's become a lot more annoying.

<img width="1640" alt="screen shot 2017-11-25 at 4 57 27 pm" src="https://user-images.githubusercontent.com/1361086/33236244-2b03d82c-d202-11e7-9bab-3ee3dd747260.png">

**Comment by hzsweers** [comment] 2017-11-26 01:01
I'd be happy to help contribute if y'all have any sense of how you want this to work implementation-wise

**Comment by jaredsburrows** [comment] 2017-11-26 01:23
@hzsweers It should not print any of that stuff at all. It shows up as errors in the IDE.

**Comment by sav007** [comment] 2019-08-22 23:37
Please try latest version with a new code generation engine https://github.com/apollographql/apollo-android/releases/tag/1.1.0

If you see the same issue pls reopen.

**Closed by sav007** 2019-08-22 23:37 UTC
Labels: Priority: Low, Type: gradle-plugin
