### ISSUE TITLE
Empty query filter to represent "match all", rather than "match nothing"?

### ISSUE THREAD

**Issue by simonmarshall** [apollographql/apollo-android#1961] opened 2020-01-30 14:24 UTC
**Is your feature request related to a problem? Please describe.**

I've got a question regarding (empty) query filters.

If I generate a query class `Q` with corresponding filter input class `F`, such that `Q`'s ctor takes an `F` instance, then I can filter on field `foo` for some value `f` and on field `bar` for some value `b` like so:

```java
F.Builder builder = F.builder();
builder.foo(TableStringFilterInput.builder().eq(f).build());
builder.bar(TableStringFilterInput.builder().eq(b).build());
Q query = new Q(builder.build());
```

This is nice.  However, if I'm trying to build my filter from a list of optional things over which I have no control, ie, `f` and/or `b` may not be provided, then I may have an empty filter, as if I had done:

```java
F.Builder builder = F.builder();
Q query = new Q(builder.build());
```

This un-intuitively matches nothing on the server, whereas I would expect it to match everything.  

**Describe the solution you'd like**

Ideally, I would like an empty filter `F` to match everything.

The only way I can see to have a filter that can match everything is by making the filter be optional, such that `Q`'s ctor takes an  `Input<F>` instance, and using `Input.absent()` when there is nothing to filter on, ie, when `f` and `b` are not provided, and similarly for the fields themselves.  However, filter construction code becomes a conditional mess:

```java
F filter;
if (f == null && b == null) {
  filter = null;
} else {
  F.Builder builder = F.builder();
  if (f != null) {
    builder.foo(TableStringFilterInput.builder().eq(f).build());
  }
  if (b != null) {
    builder.bar(TableStringFilterInput.builder().eq(b).build());
  }
  filter = builder.build();
}
Q query = new Q(Input.optional(filter));
```

(I can replace the inner individual, eg, `if (f != null) {...}`, blocks with
`builder.fooInput(Input.optional(f == null ? null : ...builder().eq(f).build());`, etc,
but there's still an unavoidable conditional.)

Or is there a better way to construct `F`?

**Comment by sav007** [comment] 2020-02-10 00:45
Well, not really sure how to solve this issue, the complication is that fields for filter `F` takes another input wrapper and without having condition there is no easy way to simplify this. 

For sure if it was Kotlin it was much nicer.

Btw you don't need to have this condition at first place:
```
if (f == null && b == null) {
  filter = null;
}
```

if I understood it right all fields in `F` are optional means Apollo will generate `Input.absent()`  as default value for them, like in [this sample](https://github.com/apollographql/apollo-android/blob/master/apollo-compiler/src/test/graphql/com/example/input_object_type/type/ReviewInput.java#L521-L529)

**Comment by simonmarshall** [comment] 2020-02-10 11:52
Hi @sav007 - thanks for the reply.  The condition you mention is necessary bcos of the general issue: that an `F` will match nothing if _none_ of the `F` fields contain a non-absent filter.  So, in that case:
- We cannot create a query `Q` with an `F`, since it will match nothing if none of the `F` fields contain a filter. Instead, we have to create a query `Q` with an `Input<F>`.
- We cannot create an `Input<F>` filter with an "empty" `F`, for the same reason.  Instead, we have to create an `Input.absent()`, which I do by creating an `Input.optional(filter)` where `filter` is `null` if `(f == null && b == null)` and is built from an `F.Builder` with `f` and `b` otherwise.  

The application of `F` is as if it applies only non-absent filter fields of `F`, unless there are _no_ non-absent filter fields, in which case it counter-intuitively applies a `true==false` filter such that nothing is matched.

It's counter-intuitive, bcos a filter containing no sub-filters should match everything in a set of items, such that each additional sub-filter can only potentially reduce the set of items that match the filter.  Instead, a filter containing no sub-filters matches _nothing_ in a set of items, such that the addition of the first sub-filter suddenly matches _some_ items and the addition of subsequent sub-filters potentially _reduces_ the set of items that match the filter.  Does that explain it better?

**Comment by martinbonnin** [comment] 2021-07-16 10:05
@simonmarshall sorry for the huuuuuuge delay. Is Kotlin an option for you? If yes, I think this is fixed in `3.0.0-alpha01`. 

If not, do you mind sharing your input type definition? We can add it as a test case as we work on https://github.com/apollographql/apollo-android/issues/2616

**Comment by simonmarshall** [comment] 2021-07-19 10:39
hi @martinbonnin, thanks for the update, it's good to see you go back to stuff.  unfortunately, kotlin isn't an option for us.

i didn't create a specific example for this particular issue (otherwise i would've attached it) but i think it was on the lines of:

`type Query { listStuff(filter: StuffFilterInput, ...): ... }`
`input StuffFilterInput { foo: TableStringFilterInput, bar: TableStringFilterInput }`

and our java filter would have to treat the absence of `foo` and `bar` specially when building the `Input`, as described above.

but i guess you knew that already...?

**Comment by martinbonnin** [comment] 2021-07-19 11:21
Thanks for the update! That stuff is hard!

If I understand correctly, the problem is that:

```java
// empty StuffFilterInput
new Query(Input.optional(StuffFilterInput.builder().build())
```

behaves differently from:

```java
// no StuffFilterInput at all
new Query(Input.absent())
```

If that's the case, I don't think we can do much inside Apollo Android itself. You could write a function that checks if the `StuffFilterInput` is empty and send `absent` in that case?

```java
StuffFilterInput filterInput = StuffFilterInput.builder(). [some code might go here to add sub-filters] .build();
Input<StuffFilterInput> input;
if (isEmpty(filterInput)) {
  input = Input.absent();
} else {
  input.optional(filterInput);
}

new Query(input)
```

**Comment by simonmarshall** [comment] 2021-07-19 13:25
i think what you're describing is the same.  i ended up writing this:

```
public static Input<StuffFilterInput> of(final QueryParameters parameters) {
   // filters are not particularly friendly: an empty filter matches nothing,
   // so we have to figure out if we have to create sub-filters or not
   final StuffFilterInput filter;
   if (parameters.getFoo() == null && parameters.getBar() == null) {
      filter = null;
   } else {
      filter = StuffFilterInput.builder()
            .fooInput(eq(parameters.getFoo()))
            .barInput(eq(parameters.getBar()))
            .build();
   }
   return Input.optional(filter);
}

private static Input<TableStringFilterInput> eq(final String s) {
   return Input.optional(s == null ? null : TableStringFilterInput.builder().eq(s).build());
}
```

which was the least messy way of doing it i came up with, but still requires the `if` for no obvious functional reason.

to me the behaviour of a filter with only absent sub-filters is counter-intuitive, as i described [here](https://github.com/apollographql/apollo-android/issues/1961#issuecomment-584087023).

**Comment by martinbonnin** [comment] 2021-07-19 13:44
I _think_ this is something you might want to take to your backend engineers? From a client point of view these two queries are different:

```graphql
query GetStuffWithEmptyFilter {
  listStuff(filter: {}) {
    id
  }
}
```

```graphql
query GetStuffWithoutFilter {
  listStuff {
    id
  }
}
```

Different servers can treat these differently. The client cannot assume anything about the result.

**Comment by simonmarshall** [comment] 2021-07-19 14:06
ok, thanks

**Comment by martinbonnin** [comment] 2021-07-19 17:54
I'm going to close this one for now. Do not hesitate to leave a message if you want me to reopen.

**Closed by martinbonnin** 2021-07-19 17:54 UTC
Labels: Java, Status: waiting for info, Type: Discussion
