### ISSUE TITLE
Gradle plugin hangs the build if the "--offline" flag is passed

### ISSUE THREAD

**Issue by ZacSweers** [apollographql/apollo-android#579] opened 2017-07-20 15:25 UTC
The `installApolloCodegen` will hang a build indefinitely if the build is run in offline mode. Would be ideal if this could be safely disabled when offline and use already-installed codegen if present

**Comment by sav007** [comment] 2017-07-20 23:04
@marwanad could you please take a look at this

**Comment by digitalbuddha** [comment] 2017-08-06 13:59
@marwanad any progress?

**Comment by marwanad** [comment] 2017-08-08 15:33
I couldn't reproduce that issue. 

I suspect it might be due to deleting the `package.json` file so the  [checks](https://github.com/apollographql/apollo-android/blob/master/apollo-gradle-plugin/src/main/java/com/apollographql/apollo/gradle/ApolloCodeGenInstallTask.java#L45) here fail. 

I'll modify those to check for the binary instead and try again tonight.

**Comment by jaredsburrows** [comment] 2017-11-01 21:38
@marwanad I was able to reproduce this just recently in my issue here: #707.

**Comment by jaredsburrows** [comment] 2017-11-01 21:42
Closing my duplicate.

Posting @marwanad suggestion here(https://github.com/apollographql/apollo-android/issues/707#issuecomment-340139137):
```
if (project.getGradle().startParameter.isOffline()) {
 afterEvaluate {
  tasks.installApolloCodegen.deleteAllActions()
 }
}
```

**Comment by hzsweers** [comment] 2017-11-26 00:59
Ping on this, really frustrating on flights :/

**Comment by jaredsburrows** [comment] 2017-11-26 01:22
@hzsweers or the Caltrain sometimes.

**Comment by sav007** [comment] 2019-08-22 23:37
Please try latest version with a new code generation engine https://github.com/apollographql/apollo-android/releases/tag/1.1.0

If you see the same issue pls reopen.

**Closed by sav007** 2019-08-22 23:37 UTC
Labels: Type: gradle-plugin
