### ISSUE TITLE
CacheKeyResolver CACHE_ONLY problem

### ISSUE THREAD

**Issue by andmyr** [apollographql/apollo-android#941] opened 2018-06-07 14:34 UTC
I have a CacheKeyResolver that looks like:
```
 resolver = new CacheKeyResolver() {
            public CacheKey fromFieldRecordSet(@NotNull ResponseField field, @NotNull Map<String, Object> recordSet) {
                if (recordSet.containsKey("id")) {
                    String typeNameAndKey = recordSet.get("__typename") + "." + recordSet.get("id");
                    return CacheKey.from(typeNameAndKey);
                }
                return CacheKey.NO_KEY;
            }
            public CacheKey fromFieldArguments(@NotNull ResponseField field, @NotNull Operation.Variables variables) {
                return CacheKey.NO_KEY;
        };
```
The first time I run a query with parameter **NETWORK_ONLY**. 
Next, I will execute the same query again, but with parameter **CACHE_ONLY** and I get the answer null.
Why the second request result is not taken from the cache?
At the second request, only method _fromFieldArguments_ is executed, method _fromFieldRecordSet_ is not executed.

**Comment by sav007** [comment] 2018-06-08 18:08
Could you please provide the GraphQL query?

**Comment by sav007** [comment] 2018-06-08 18:13
As well we have tests that verify exactly your case https://github.com/apollographql/apollo-android/blob/master/apollo-integration/src/test/java/com/apollographql/apollo/NormalizedCacheTestCase.java#L104

https://github.com/apollographql/apollo-android/blob/master/apollo-integration/src/test/java/com/apollographql/apollo/Utils.java#L72
maybe we missing something

**Comment by andmyr** [comment] 2018-06-09 06:06
```
query UserDetails($user: UserInput, $cursor: CursorInput) {
    user(input: $user) {
        ...UserDetails
        ...UserLastLikedSongs
        ...UserFollowing
    }
}

fragment UserDetails on UserOutput {
    id
    name
    image
    displayName
    email
    birthday
    created
    country
    counters {
        followers,
        followings,
        played
        }
    options {
        arcades {
            genres
        }
    }
    profiles{
          google,
          facebook
        }
}

fragment UserFollowing on UserOutput {
    id
    following(cursor: $cursor) {
        nodes {
            id
            name
            image
       }, cursor {
            id,
            size,
            page,
            next
        }
    }
}

fragment UserLoudest on UserOutput {
    id,
    loudest: playlist(cursor: $cursor) {
        nodes {
            id
            name
            image
            audio
            artists {
                id
                name
            }
        },
        cursor {
            id,
            size,
            page,
            next
        }
    }
}

fragment UserLastLikedSongs on UserOutput {
    id,
    songs: playlist(cursor: $cursor) {
        nodes {
            id
            name
            image
            audio
            artists {
                id
                name
            },
        }
        cursor {
            id,
            size,
            page,
            next
        }
    }
}

```

**Comment by sav007** [comment] 2018-06-11 11:17
I see couple input objects:
```
query UserDetails($user: UserInput, $cursor: CursorInput) {
    user(input: $user)
```

Are you sure you have identical input objects for both queries?

**Comment by sav007** [comment] 2018-06-11 11:36
Let me check smth, but not sure we support the input objects as a cache key for the queries

**Comment by sav007** [comment] 2018-07-17 03:38
Possible duplicate of https://github.com/apollographql/apollo-android/issues/977

**Closed** 2018-08-03 01:11 UTC
