### ISSUE TITLE
Query returning an Interface type not working properly

### ISSUE THREAD

**Issue by OmarHP** [apollographql/apollo-android#1469] opened 2019-07-31 18:30 UTC
I have the following query which returns an [interface type](https://www.apollographql.com/docs/apollo-server/features/unions-interfaces/#interface-type) (`CalendarEvent`) and there are three possible types that implement this interface `ICalCalendarEvent`, `ReservationCalendarEvent` and `AvailabilityEvent`. Apollo used to create only the fragment that matches the `resolveType` but now it creates all them, filling with nulls the fields of the fragments that don't match the "resolveType". Is this a bug or something has changed in 1.0.2?

```
query CalendarQuery($someParam: String!) {
  pxCalendar(someParam: $someParam) {
   	...calendarFragment
  }
}

fragment calendarFragment on CalendarEvent {
    content
    startDate
    endDate  
  	...iCalCalendarEventFragment
  	...reservationCalendarEventFragment
  	...availabilityEventFragment
}

fragment iCalCalendarEventFragment on ICalCalendarEvent {
  color
  name
}

fragment availabilityEventFragment on AvailabilityEvent {
  id
}

fragment reservationCalendarEventFragment on ReservationCalendarEvent {
  resId
}
```

I looked at the code apollo generates and it doesn't seem to be using the `conditionalType` anywhere, so I guess that's why the three fragments are being created. 

`CalendarFragment.Fragments.Mapper#map`
```
@NotNull
public CalendarFragment.Fragments map(ResponseReader reader, @NotNull String conditionalType) {
  ICalCalendarEventFragment iCalCalendarEventFragment = this.iCalCalendarEventFragmentFieldMapper.map(reader);
  ReservationCalendarEventFragment reservationCalendarEventFragment = this.reservationCalendarEventFragmentFieldMapper.map(reader);
  AvailabilityEventFragment availabilityEventFragment = this.availabilityEventFragmentFieldMapper.map(reader);
  return new CalendarFragment.Fragments(iCalCalendarEventFragment, reservationCalendarEventFragment, availabilityEventFragment);
            }
```

**UPDATE:**

I downgrade the version to 1.0.0 and looked at the same autogenerated part of the code and in fact, it uses the `conditionalType` to know which fragment to create

```
@Override
public @NotNull Fragments map(ResponseReader reader, @NotNull String conditionalType) {
    ICalCalendarEventFragment iCalCalendarEventFragment = null;
    ReservationCalendarEventFragment reservationCalendarEventFragment = null;
    AvailabilityEventFragment availabilityEventFragment = null;
    if (ICalCalendarEventFragment.POSSIBLE_TYPES.contains(conditionalType)) {
        iCalCalendarEventFragment = iCalCalendarEventFragmentFieldMapper.map(reader);
    }
    if (ReservationCalendarEventFragment.POSSIBLE_TYPES.contains(conditionalType)) {
        reservationCalendarEventFragment = reservationCalendarEventFragmentFieldMapper.map(reader);
    }
    if (AvailabilityEventFragment.POSSIBLE_TYPES.contains(conditionalType)) {
        availabilityEventFragment = availabilityEventFragmentFieldMapper.map(reader);
    }
    return new Fragments(iCalCalendarEventFragment, reservationCalendarEventFragment, availabilityEventFragment);
}
```

**Comment by sav007** [comment] 2019-08-02 21:01
Shoot I guess it's a regression introduced by  https://github.com/apollographql/apollo-android/pull/1410

**Comment by sav007** [comment] 2019-08-02 21:29
Hm, I wasn't able to reproduce this issue on our samples, having this (where `Character` interface, `Human` is implementation of this interface:
```
query TestQuery {
  hero {
    ...CharacterDetails
  }
}

fragment CharacterDetails on Character {
    ...HeroDetails
    ...HumanDetails
}

fragment HumanDetails on Human {
  name
}

fragment HeroDetails on Character {
  name
}
```

Generates correctly, for `HumanDetails` it will check `conditionalType` for `HeroDetails` as it defined on the same type as `CharacterDetails` it won't be optional:
```
public @NotNull Fragments map(ResponseReader reader, @NotNull String conditionalType) {
        HeroDetails heroDetails = heroDetailsFieldMapper.map(reader);
        HumanDetails humanDetails = null;
        if (HumanDetails.POSSIBLE_TYPES.contains(conditionalType)) {
          humanDetails = humanDetailsFieldMapper.map(reader);
        }
        return new Fragments(Utils.checkNotNull(heroDetails, "heroDetails == null"), humanDetails);
      }
```

Is there any way I can grab your schema.json to try reproduce on your example?

**Comment by OmarHP** [comment] 2019-08-21 18:16
Hi @sav007, thanks for taking a look. Unfortunately, I'm not allowed to share the whole schema. This is what I could get

[partial_schema.json.txt](https://github.com/apollographql/apollo-android/files/3526662/partial_schema.json.txt)

Basically, it only contains the part where this type is defined.

**Comment by sav007** [comment] 2019-09-27 01:40
I think this is a duplicate of https://github.com/apollographql/apollo-android/issues/1584 that was fixed in https://github.com/apollographql/apollo-android/pull/1608.

Closing for now, pls try latest snapshot.

**Closed by sav007** 2019-09-27 01:40 UTC
Labels: Possible bug, investigation
