### ISSUE TITLE
Quotes missing after decoding LinkedHashMap

### ISSUE THREAD

**Issue by anup1245** [apollographql/apollo-android#2403] opened 2020-06-26 18:57 UTC
Hi,
Im facing this issue on 2.2.0

When decoding the "value", which is of type LinkedHashMap, the quotes are missing and hence unable to parse the json

```java
private CustomTypeAdapter dataMapTypeAdapter = new CustomTypeAdapter() {

    @Override
    public LinkedTreeMap decode(@NotNull CustomTypeValue value) {
        return new Gson().fromJson(value.value.toString(), LinkedTreeMap.class);
    }

    @Nonnull
    @Override
    public CustomTypeValue encode(@Nonnull LinkedTreeMap value) {
        return new CustomTypeValue.GraphQLString(new Gson().toJsonTree(value).getAsJsonObject().toString());
    }
};
```

value is of type LinkedHashMap and after converting to string it comes as {test=value}

**Comment by martinbonnin** [comment] 2020-06-29 15:32
Hi! That might be the expected behaviour. It looks like your server is returning a json object and not a string?

```
{
  "key": {
    "test": "value"
  }
}
```
vs
```
{
  "key": "{\"test\": \"value\"}"
}
```

If that's what the server is sending, you can get a LinkedTreeMap from a GraphQLJsonObject with something like this:

```
LinkedTreeMap map = LinkedTreeMap()
map.putAll(((CustomTypeValue.GraphQLJsonObject)value).value) // value.value should be a map
```

**Comment by martinbonnin** [comment] 2020-07-27 09:12
@anup1245 I'm closing this issue, let me know if you want me to reopen it.

**Closed by martinbonnin** 2020-07-27 09:12 UTC
Labels: Status: waiting for info, Type: Bug, Type: Investigation
