### ISSUE TITLE
No setter methods in Apollo Generated classes for android

### ISSUE THREAD

**Issue by skybloouu** [apollographql/apollo-android#959] opened 2018-06-21 15:28 UTC
I've been using Apollo-graphql on android and I can't find any setter methods in the classes generated by Apollo. However, iOS has setter methods in the classes generated by Apollo.

Is there any way I can enable setter methods in those classes? Also the Collections are immutable and its very difficult to handle pagination because of it.

**Comment by digitalbuddha** [comment] 2018-06-22 18:32
This is by design, all data models generated by Apollo are immutable for thread safety. If you need to mutate models I recommend mapping to your own data models which you have control over. 

Could you give more info about what the problem is with pagination?

**Comment by skybloouu** [comment] 2018-06-27 06:00
@digitalbuddha I've one API which returns me "All categories" and also "Categorised" data. When $page is 0, I get "All categories" data and for pagination I use same API call to get "Categorised" data by incrementing $page. The "Content " from response of "Categorised" data has to be appended to the "Category" list "Content" of "All Categories" and since "All Categories" class is Apollo generated and is immutable, I can't append the Content. 
Similarly, when user performs any action on the list item e.g Like, DisLike, I can't update the value of data class generated by Apollo.

**Comment by AlphaGao1993** [comment] 2018-07-04 14:24
Could you provide setter method by a configurable item for models generate? If we dont't need setter, then we can close it.

**Comment by sav007** [comment] 2018-07-17 03:42
Btw if it can help you with this config:
```
generateModelBuilder = true
```

All models will be generated with Builders for example:
https://github.com/apollographql/apollo-android/blob/master/apollo-compiler/src/test/graphql/com/example/fragment_with_inline_fragment/fragment/HeroDetails.java#L233

So to mutate you can do this `hero.toBuilder().name("newName).build()`

**Comment by skybloouu** [comment] 2018-07-18 20:02
@sav007 I've considered your suggestion and tried to update LikedStatus using myModel.toBuilder().likeStatus("1").build();
it was "0" before and even after running it the value remains 0 and doesn't update. I've debugged the code and it runs through the code, still myModel's value isn't updated

**Comment by sav007** [comment] 2018-07-18 20:34
Are you sure that you using the object returned back by `build()` function as it different instance.

**Comment by sav007** [comment] 2018-10-23 22:28
Closing due to inactivity.

**Closed by sav007** 2018-10-23 22:28 UTC
Labels: Type: Discussion
