### ISSUE TITLE
Bump the gradle version

### ISSUE THREAD

**Issue by omegasoft7** [apollographql/apollo-android#1219] opened 2019-02-28 08:46 UTC
I receive the following error after bumping my gradle version to 3.5.x

```* What went wrong:
A problem occurred configuring project ':common-apollo'.
> Could not resolve all artifacts for configuration ':common-apollo:classpath'.
   > Could not find com.android.tools.build:gradle:3.2.1.
     Searched in the following locations:
       - https://jcenter.bintray.com/com/android/tools/build/gradle/3.2.1/gradle-3.2.1.pom
       - https://jcenter.bintray.com/com/android/tools/build/gradle/3.2.1/gradle-3.2.1.jar
     Required by:
         project :common-apollo > com.apollographql.apollo:apollo-gradle-plugin:1.0.0-alpha5```

**Comment by khajamasroorahmed** [comment] 2019-04-04 02:51
Duplicate of #1179

**Comment by sav007** [comment] 2019-05-30 19:30
It was updated to 3.3.0

**Closed by sav007** 2019-05-30 19:30 UTC
