### ISSUE TITLE
Subscription throws ApolloNetworkException

### ISSUE THREAD

**Issue by MohamedGamalElsayed** [apollographql/apollo-android#2407] opened 2020-06-29 12:41 UTC
**Summary**
Subscription works normally in the beginning, but throws ApolloNetworkException if there're no updates for 1 minute.

**Version**
2.1.0

**Description**
Using Android Apollo subscription's integration with Coroutines:  
* Subscription starts normally and works as expected.
* Client receives updates.
* If there're no updates for > 55 sec subscription ends with an exception.
* Subscription throws: com.apollographql.apollo.exception.ApolloNetworkException: Subscription failed

**Comment by martinbonnin** [comment] 2020-06-29 12:46
Are you using `apollo-runtime-kotlin` ? If yes, you might need https://github.com/apollographql/apollo-android/pull/2388 that will be included in next version. You can also try the [snapshots](https://github.com/apollographql/apollo-android#releases).

**Comment by MohamedGamalElsayed** [comment] 2020-06-29 13:51
> apollo-runtime-kotlin

I use `apollo-runtime` and `apollo-coroutines-support`, will try snapshots and wait for the next version 👍

**Comment by martinbonnin** [comment] 2020-06-29 13:55
Ah, it's something else then, don't bother with the SNAPSHOTs/new version, I doubt there's anything different regarding the regular `apollo-runtime` there. 

Do you have the complete stacktrace? It looks like a Keep-Alive issue but maybe it's something else. Is your API public by any chance so I can try to reproduce?

**Comment by MohamedGamalElsayed** [comment] 2020-06-29 14:04
Unfortunately my API is not public, but this issue happens with me in 2 projects with 2 different APIs

> Do you have the complete stacktrace? 

`E/AndroidRuntime: FATAL EXCEPTION: main
    com.apollographql.apollo.exception.ApolloNetworkException: Subscription failed
        at com.apollographql.apollo.internal.RealApolloSubscriptionCall$SubscriptionManagerCallback.onNetworkError(RealApolloSubscriptionCall.java:246)
        at com.apollographql.apollo.internal.subscription.RealSubscriptionManager$SubscriptionRecord.notifyOnNetworkError(RealSubscriptionManager.java:524)
        at com.apollographql.apollo.internal.subscription.RealSubscriptionManager.onTransportFailure(RealSubscriptionManager.java:296)
        at com.apollographql.apollo.internal.subscription.RealSubscriptionManager$SubscriptionTransportCallback$2.run(RealSubscriptionManager.java:556)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.EOFException
        at okio.RealBufferedSource.require(RealBufferedSource.kt:201)
        at okio.RealBufferedSource.readByte(RealBufferedSource.kt:210)
        at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:113)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:96)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:247)
        at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:181)
        at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) `

**Comment by martinbonnin** [comment] 2020-06-30 09:12
Can you check this is not something with the server? Does it work well if you run the subscription in iOS/GraphiQL/Playground?

**Comment by MohamedGamalElsayed** [comment] 2020-06-30 09:42
Yes, we already checked the server

> Does it work well if you run the subscription in iOS/GraphiQL/Playground?

Yeah, it works well with iOS and Playground

**Comment by martinbonnin** [comment] 2020-06-30 10:12
What server are you using? Maybe I can reproduce if it's linked to a particular server?

**Comment by MohamedGamalElsayed** [comment] 2020-07-02 15:34
Apollo server

**Comment by MerveGencer** [comment] 2020-09-22 10:42
I have this issue when my network connection is lost during a subscription. All my subscriptions subscribes in a try/catch block but this issue is happening after the subscription happens, and I cannot handle it even if I want to.

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.banba.operation.staging, PID: 15295
    com.apollographql.apollo.exception.ApolloNetworkException: Subscription failed
        at com.apollographql.apollo.internal.RealApolloSubscriptionCall$SubscriptionManagerCallback.onNetworkError(RealApolloSubscriptionCall.java:246)
        at com.apollographql.apollo.internal.subscription.RealSubscriptionManager$SubscriptionRecord.notifyOnNetworkError(RealSubscriptionManager.java:524)
        at com.apollographql.apollo.internal.subscription.RealSubscriptionManager.onTransportFailure(RealSubscriptionManager.java:296)
        at com.apollographql.apollo.internal.subscription.RealSubscriptionManager$SubscriptionTransportCallback$2.run(RealSubscriptionManager.java:556)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.net.SocketException: Software caused connection abort
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
        at java.net.SocketInputStream.read(SocketInputStream.java:176)
        at java.net.SocketInputStream.read(SocketInputStream.java:144)
        at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:898)
        at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:862)
        at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:777)
        at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:750)
        at okio.InputStreamSource.read(JvmOkio.kt:90)
        at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
        at okio.RealBufferedSource.request(RealBufferedSource.kt:206)
        at okio.RealBufferedSource.require(RealBufferedSource.kt:199)
        at okio.RealBufferedSource.readByte(RealBufferedSource.kt:209)
        at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:113)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:96)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:247)
        at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:181)
        at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) `

**Comment by MohamedGamalElsayed** [comment] 2020-10-02 15:10
@martinbonnin I'm sorry it was our issue not the library's one. Had to update you to close the issue 👍🏼

**Closed** 2020-10-02 15:10 UTC
Labels: Component: Runtime, Type: Bug, Type: Investigation

**Comment by itslonua** [comment] 2023-01-17 09:15
I have just reproduced the same

**Comment by cannyRamji** [comment] 2023-12-18 07:53
@MohamedGamalElsayed Can you provide some insight on root cause we are also facing the same
