### ISSUE TITLE
Builders are always generated regardless of the flag

### ISSUE THREAD

**Issue by tasomaniac** [apollographql/apollo-android#1477] opened 2019-08-06 07:17 UTC
Generating Builders were introduced here: https://github.com/apollographql/apollo-android/pull/622 According to the description of the PR and the default value of the Property, Builder generation should be off by default. 

### Problem 

Builders are always generated regardless of `generateModelBuilder` property.

**Comment by ralphie9224** [comment] 2019-08-22 18:37
Interested in taking a look at this one. Is anybody else on it?

**Comment by sav007** [comment] 2019-08-23 16:40
no, pls go ahead!

**Comment by ralphie9224** [comment] 2019-09-06 02:57
@tasomaniac Just to confirm. Is the issue here that the flag isn't defaulting to `false`? So the Builders are built by default? Or that even with the flag being set to `false` the builders are being generated anyways?

**Comment by tasomaniac** [comment] 2019-09-06 06:28
2nd one. Even if it is explicitly set to false, they're generated. Btw, I feel like there might be different Builders at different levels on Apollo.

**Comment by martinbonnin** [comment] 2019-09-06 08:12
@tasomaniac I had the same observation. The "top-level" builders are always generated. Some other (more nested) actually respect the `generateModelBuilders` flag. Maybe it's the expected behavior and the top-level Builders are useful for building Input/Queries.

**Comment by tasomaniac** [comment] 2019-09-06 11:16
I think they should all go together. Builders help if the number of properties are bigger. Enabling them is a choice and why not enable all if needed? 

Or would you prefer 2 separate configuration?

For us, we never use builders for queries and inputs so far. I would like to remove them if not needed.

**Comment by martinbonnin** [comment] 2019-09-06 11:35
IIRC, the top-level builders have always been there. Then the nested builders were added and I guess we didn't want to make it the default so we ended up with decoupled builders. 

It would be nicer to have a "all or nothing" setting but this is a breaking change... Unless we make the default "all builders" ? Users relying on top-level builders would still be able to use them. Others would get a bit more bytecode/methods but proguard/r8 should strip everything that's not needed. And they can opt-out with `generateModelBuilders=false` in all cases.

**Comment by tasomaniac** [comment] 2019-09-06 14:31
The history makes sense a lot. We could as well close this since it is not the most important. I just think that for the long run, consistency would be nice. 

Also for Kotlin models, do we also have Builders. If we don't have Builders for Kotlin at all (which is what people usually do) then this would somewhat affect the decision.

**Comment by martinbonnin** [comment] 2019-09-06 14:59
Kotlin has no builders at all since the models are data classes.

**Comment by ralphie9224** [comment] 2019-09-06 18:56
So does that mean we are closing this out?

**Comment by sav007** [comment] 2019-09-18 14:35
Yeah I guess we can close it.

**Closed by sav007** 2019-09-18 14:35 UTC
Labels: Type: Bug, Type: compiler
